### ISSUE TITLE
Bildupload funktioniert nicht

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#103]
Ich hatte vorhin mehrfach versucht, ein Bild aus dem iPhone in ein Posting einzubinden – vergebens. Nach dem Upload erschien das Bild nicht im Posting; auch keine Fehlermeldung.

Ist da wieder eine Größenbeschränkung am Werk, die Bilduploads verhindert?

**Comment by ckruse** [comment]
Ich kann das nicht nachvollziehen. Hast du ein Beispiel-Bild irgendwo, mit dem ich das testen könnte?

**Comment by MatthiasApsel** [comment]
Ich kann das bestätigen. Auch ich kann kein Bild hochladen, dass die Abmessungen von 4032 x 1960 hat und 1,5 MB groß ist.

**Comment by ckruse** [comment]
Kannst du mir so ein Bild mal zukommen lassen, damit ich das testen kann? Ich kann das nachwievor nicht nachvollziehen.

**Comment by ckruse** [comment]
@gunnarbittersmann hast du das Bild auch via Zwischenablage eingefügt?

**Comment by ckruse** [comment]
Hintergrund: ich habe das jetzt nachvollziehen können, wenn ich die Zwischenablage benutze statt drag'n'drop oder den Button. Und das führt dazu, dass ich das Bild (ursprünglich jpg, 1,5mb) als PNG bekomme mit über 12mb 🤨

**Comment by ckruse** [comment]
Für Webkit ist das definiertes verhalten: https://trac.webkit.org/changeset/222656/webkit

**Comment by ckruse** [comment]
Für Chrome ist es auch bekannt: https://stackoverflow.com/questions/34508763/why-chrome-convert-the-image-data-to-image-png-mime-type-when-paste

Für Firefox hab ichs nur in die andere Richtung finden können: https://bugzilla.mozilla.org/show_bug.cgi?id=344248 das aber lässt vermuten, dass es da absichtlich auch nicht anders ist…

Das grundsätzliche Problem ist wohl, dass im Clipboard die Bild-Daten unkomprimiert vorliegen, und je nach OS entweder als Bitmap (etwa Windows) oder TIFF (macOS). Um das zu vereinheitlichen wandeln die Browser wohl um in PNG.

**Comment by ckruse** [comment]
Das einzige, was mir da einfällt, ist das hochsetzen des Upload-Limits für multipart-Requests. Das habe ich jetzt mal getan, auf 100mb… alles andere als befriedigend, aber mehr fällt mir da nicht sinnvolles ein
