### ISSUE TITLE
Neuer Beitrag in IE 11 nicht möglich

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#106]
Im IE 11 kann man keinen neuen Beitrag erstellen, weil die Tagauswahl nicht angezeigt wird. Vielleicht sollte man darauf hinweisen (ähnlich wie browser-update.org).

**Comment by ckruse** [comment]
Oh man… *seufz*

**Comment by MatthiasApsel** [comment]
Aber ich würd da nicht so sehr viel investieren. Es scheint an forEach zu liegen. Und alle forEach auf for umzuschreiben ist sicher nicht das, was man will.

**Comment by ckruse** [comment]
nein, ich nutze so einige Features, die der IE11 nicht kann, unter anderem `new Event`, `NodeList.prototype.forEach`, usw.

Ich bin gerade dabei, alles JS für ältere Browser abzubrechen und einen Hinweis einzublenden.
