### ISSUE TITLE
Es sollte auch Foren ohne Verpflichtung auf Tags geben

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#108]

**Comment by MatthiasApsel** [comment]
Wahrscheinlich ist "Kein Tag notwendig" noch ein besonderer Fall. Jetzt gibt es einen 500er ("Ooops, irgendwas ist schief gegangen.) Laut Audit-Log wird der Beitrag erstellt, kann aber nicht gefunden werden (https://forum.selfhtml.org/intern/2019/aug/01/tags-notwendig/1754447?view_all=true#m1754447)

**Comment by ckruse** [comment]
Nö, das sollte einfach gehen. Ich habe das bei mir lokal getestet. Da muss was anderes schief gelaufen sein.

**Comment by ckruse** [comment]
Die ganzen alten Beiträge von z.B. 1998 haben ja auch keine Tags

**Comment by MatthiasApsel** [comment]
Hm. Soll ich noch mal probieren?

**Comment by ckruse** [comment]
Ich mache gerade ein Release. Da ist das Auditing fehlerhaft gewesen.
