### ISSUE TITLE
Falscher Monat in Archivabfrage - internal server error

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#11]
Sowas sollte mit einer "page not found" Meldung quittiert werden. URLs werden gelegentlich vom User übertippt.

Z.B. /entwicklung/2019/mai (statt may) gibt Internal Server Error

Die page not found Seite braucht ohnehin noch ein Design, aber das weißt Du sicher :)

**Comment by ckruse** [comment]
Oh, good catch.

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!
