### ISSUE TITLE
XSS im Archiv

### ISSUE THREAD

**Issue by molily** [ckruse/cforum_ex#110]
Hallo,

mir ist augefallen, dass es im Archiv ein Posting zum Thema XSS gibt, das selber XSS darstellt:

https://forum.selfhtml.org/self/2014/jun/22/php-array-an-javascript-function-uebergeben/1614264#m1614264

Wenn man die Seite öffnet, wird `alert(/XSS/)` ausgeführt. Dieser Code stammt aus dem Text eines Postings. Dessen HTML-Quellcode sieht so aus:

```
<blockquote>
<p>require_once 'Zend/Loader/StandardAutoloader.php';<br>
loader = new Zend\Loader\StandardAutoloader(array('autoregister_zf' => true));  
loader-&gt;register();<br>
class ToJason {<br>
    public foo = '</script><script>alert(/XSS/)</script>';  
}  
phpNative = new ToJason;<br>
json = Zend\Json\Json::encode(phpNative);<br>
var_dump($json);</p>
</blockquote>
```

Das `</script><script>` im blockquote wird nicht HTML-maskiert, daher wird der JS-Code ausgeführt.

Warum das gerade dort passiert und ob auch anderer Code im Archiv ausgeführt wird, kann ich nicht sagen.

Allgemein würde ich empfehlen, eine Content Security Policy zu verwenden, die die Ausführung von Inline-Scripten verhindert, denen eine gewisse Nonce oder ein gewisser Hash fehlt.

**Comment by ckruse** [comment]
Hm. Verwirrend, das dürfte nicht passieren, ich habe die HTML-Parser in markdown-it eigentlich deaktiviert. Danke, ich muss das auch mal prüfen…

Bzgl der CSP: ja, das ist wohl eine gute Idee. Habe ich schlicht nicht dran gedacht.

**Comment by ckruse** [comment]
Autsch. Das ist das Katex-Plugin… das interpretiert das wohl als TeX, wegen der `$`

**Comment by ckruse** [comment]
Ich habe KaTeX zeitweise deaktiviert. Ich habe gerade keine Zeit eine Alternative zu bauen. Ich schaue heute Abend mal genauer, ob und wie wir wieder MathJax einsetzen können; reines Client-seitiges rendern von LaTeX wäre für mich OK.

**Comment by ckruse** [comment]
P.S.: schön mal wieder was von dir zu hören :-)
