### ISSUE TITLE
Escapetes Dollarzeichen aktiviert Latex

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#111]
Wenn ich ein escapetes Doppeldollar (also die Zeichenfolge Backslash-Dollar-Backslash-Dollar) zweimal in einem Absatz habe, wird Latex aktiv.

Das schreibe ich: Das ist \\\$\\\$ein Test\\\$\\\$ für Latex

Das soll rauskommen: Das ist Das ist \$\$ein Test\$\$ für Latex

Das kommt raus: 
![image](https://user-images.githubusercontent.com/34056213/62929719-52f78d00-bdbb-11e9-8796-70064cc36e7b.png)

**Comment by ckruse** [comment]
Es sind doppelte Backslashes notwendig.
