### ISSUE TITLE
Adventskalender-Layout braucht Verbesserung

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#1119]
Hallo Christian,

(Hinweis, ich schreibe nicht mehr als "any club member", sondern seit vorgestern als 2. Vorsitzender).

Du hast 2021 als Workaround für lange Link-Inhalte ein line-break:anywhere in den Adventskalender gesetzt, und das ist eigentlich ein ganz schlechter Kompromiss. Damals sind wir nicht darauf gekommen, aber ich denke, dass man vom Kalenderautor erwarten kann, einen umbrechbaren Ersatztext zu benutzen oder bei wirklich langen Worten ein Soft Hyphen (Alt+0179) einzufügen. Das line-break:anywhere war ein schneller Fix, aber es lässt den Adventskalender aussehen, als wüssten wir nichts von richtigem Umbruch.

Ein zweiter Punkt sind Listen im Adventskalender. Da kann man sich mit manuellen Bullets behelfen, aber ich denke, mit ein wenig Zusatz-CSS kriegt man das hin. Ich habe das in meinen persönlichen Einstellungen mal vertestet, und ich hätte das gerne als externe CSS Resource in den Foreneinstellungen hinterlegt, um Dich nicht behelligen zu müssen, aber das wird nicht akzeptiert. 

Ich wollte  
<https://wiki.selfhtml.org/wiki/Beispiel:Advent.css>  
in Form von   
<https://wiki.selfhtml.org/extensions/Selfhtml/example.php/Beispiel:Advent.css>

hinzufügen, aber das wurde von der CSP abgewiesen, weil die Direktive `style-src 'self' 'unsafe-inline'` das nicht zulässt. Und inline-CSS, so wie es für User möglich ist, scheint nicht vorgesehen zu sein. Das Feature "zusätzliche CSS-Resourcen" scheint damit grundsätzlich an Sicherheitsbedenken zu scheitern. Es sei denn, man ersetzt in der CSP das `style-src 'self' 'inline-unsafe'` durch `style-src *.selfhtml.org 'inline-unsafe'`. Weil es nicht funktionierte, habe ich jetzt erstmal die "Default" Checkbox wieder gesetzt.

Die Alternative wäre, die Styles aus dem Beispiel:Advent.css ins Forenstylesheet zu übernehmen, in dem Fall würde man das sicherlich etwas konstruktiver formulieren und nicht mit Überschreibungen arbeiten müssen. ~~Ich kann versuchen, dafür eine Vorlage zu machen.~~ Ich bereite dafür gerade einen Pull-Request vor.

Kriegen wir das für den diesjährigen Adventskalender hin? Was ist für Dich die realistische Lösung? Ich weiß nicht wie Du zeitlich beansprucht bist.

Liebe Grüße
Rolf

**Comment by ckruse** [comment]
Ich habe das CSS übernommen und den Header angepasst.
