### ISSUE TITLE
Liste der auf einen Beitrag verweisenden Beiträge wird nicht aktualisiert

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#115]
![grafik](https://user-images.githubusercontent.com/2847625/63881013-30768e00-c9cf-11e9-897c-b3b59b575d42.png)
Auch https://forum.selfhtml.org/self/2019/aug/28/verstandigungsproblem-klicken-beruhren-antippen-scrollen-wischen/1756628#m1756628 verweist auf diesen Beitrag.

**Comment by ckruse** [comment]
Ja, ich weiß… ich habe dieses Feature noch gar nicht eingebaut. Und ich bin mir auch nicht so richtig sicher, ob es sinnvoll wäre, diese Funktion überhaupt wieder einzubauen und nich komplett zu droppen. Ich habe den Eindruck, dass das keinen Mehrwert bringt. Der Gedanke war ja, dass man ggfls in späteren Postings dann mehr Infos findet. Aber realistisch betrachtet habe ich noch keinen einzelnen Fall gesehen, in dem das passiert wäre. Außerdem glaube ich auch nicht, dass ein Nicht-Regular sich überhaupt die Mühe machen würde, den Links zu folgen.

**Comment by ckruse** [comment]
Referenzen wurden vollständig entfernt…

**Comment by MatthiasApsel** [comment]
Ergänzung: 

CK: hast du keine Meinung zu https://github.com/ckruse/cforum_ex/issues/115?
6. SEP. 14:10
MA: Nö. Ich glaube, das war damals meine Idee, sehe aber persönlich auch nicht den Drang, den Links zu folgen, vor allem, weil man dann ja wieder irgendwo mitten in einem Thread landet. Wenn du also meinst, weg damit, dann weg damit.
6. SEP. 14:15
CK: genau das hab ich halt auch beobachtet…
6. SEP. 14:16
CK: und es macht alles unübersichtlicher
6. SEP. 14:18

**Comment by Davennix** [comment]
a
