### ISSUE TITLE
Gelesene Beiträge auf ungelesen setzen

### ISSUE THREAD

**Issue by MarcHaunschild** [ckruse/cforum_ex#116]
Als User möchte ich Beiträge, die ich erst später beantworten möchte auf „ungelesen“ setzen können.
Alternativ wären auch „Wiedervorlage“ oder eine „To-Do“-List denkbar, denen man Beiträge hinzufügen kann.
Aber die erste Möglichkeit wäre die einfachste und ist aus ähnlichen Kontexten (email) bekannt.

**Comment by MatthiasApsel** [comment]
Gibt es einen Grund, warum die Bedienelemente jetzt in 2 div class="controls" aufgeteilt sind?

**Comment by ckruse** [comment]
Ja. Mehr Übersicht. Oben sind die Dinge, die etwas auslösen, das nicht spezifisch für den User ist und unten sind die Dinge, die etwas auslösen, das spezifisch für den User ist.

**Comment by MatthiasApsel** [comment]
Ah. Leuchtet ein. Ich habs trotzdem in einer Zeile :-D
