### ISSUE TITLE
Performance des Nested-View lässt zu wünschen übrig

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#117]
...um nicht zu sagen: sie ist grottig.

Der Aufruf des aktuellen [Gender-Threads](https://forum.selfhtml.org/self/2019/aug/29/barrierefreie-darstellung-des-gendersternchens/1756737#m1756737) dauert ewig.

Ladezeit des Hauptdokuments:
![image](https://user-images.githubusercontent.com/34056213/64476874-a54a8480-d194-11e9-9ce1-673fbb0ca5cd.png)

Chrome Statusleiste am Ende:
![image](https://user-images.githubusercontent.com/34056213/64476864-7cc28a80-d194-11e9-87a6-5b3407996999.png)

Die Ressourcen kamen - außer dem Hauptdokument - aus dem Browsercache. 

Ausgeführt auf einem 50MBit DSL Anschluss, der zum Ausführungszeitpunkt exklusiv von mir genutzt wurde. Es gab auch keinen signifikanten anderen Netztraffic auf meinem PC. Sprich: Das war nicht mein lokales Problem. Die lange Ladezeit des Hauptdokuments spricht dafür, dass der Server sehr lange braucht, um die Response zu komponieren. 

LG
Rolf

**Comment by ckruse** [comment]
Die Nested-View muss *alle* Postings rendern. Das sind im verlinkten Thread 300 Postings. Der NodeJS-Pool, der das rendern übernimmt, besteht aus 30 Workern. Das sind 10 Postings pro Worker. Selbst wenn man davon ausgeht, dass der Pool vollständig frei ist: das dauert halt eine Weile…

Wenn man das beschleunigen will, gibt es nur zwei Ansätze: on-demand nachladen via JS oder das Rendering-Ergebnis cachen, so dass man nicht jedes Posting jedesmal rendern muss.

Variante 1 hat den Nachteil, dass es nur mit JS funktioniert. Variante 2 hat zwei große Nachteile: das Caching ist erstens sehr Speicher-hungrig und zweitens verhindert man damit, dass man User-spezifische Dinge in das Rendering einbauen kann. Etwa das hochlichten von Mentions von hervorgehobenen Usern fällt damit flach.

Ich denke eher, wir leben damit, dass solche grenzwertigen Threads in der Nested-Ansicht eine Weile brauchen.

**Comment by Rolf-B** [comment]
30 Worker ist eine Menge, da sollte man mehr erwarten. Also... weniger (Zeit). Es sei denn, das Forum hat so viel Traffic, dass die auf dem letzten Loch pfeifen.

Es geht mir auch nicht um diesen Einzelfall, er könnte aber grundsätzliche Flaschenhälse im System sichtbar machen. Hast du Messpunkte, mit denen du das beobachten kannst?

**Comment by ckruse** [comment]
Ja, es gibt umfangreiches Monitoring. Die Response-Time im Mittel liegt bei etwa 100ms. Der Worst-Case liegt bei etwa 3800ms.

![Bildschirmfoto 2019-09-09 um 08 49 21](https://user-images.githubusercontent.com/175095/64508912-e058cf00-d2de-11e9-9fda-845bcdc41956.png)

Das ist viel, aber wie ich schon schrieb: da lässt sich auch nicht so richtig viel machen. Das rendering ist schon parallelisiert:

~~~elixir
    prerendered =
      conn.assigns.thread.messages
      |> Task.async_stream(fn msg -> {msg.message_id, Cforum.MarkdownRenderer.to_html(msg, conn)} end, ordered: false)
      |> Enum.reduce(%{}, fn {:ok, {msg_id, cnt}}, acc -> Map.put(acc, msg_id, cnt) end)
~~~

Ich könnte höchstens noch mit der Pool-Size spielen; aber eigentlich verhungert da nichts. Das Problem sind halt wirklich so Riesen-Threads.

> Es geht mir nicht um diesen Einzelfall, er könnte aber grundsätzliche Flaschenhälse im System sichtbar machen.

Grundsätzlich ist der Flaschenhals das serverseitige Rendering. Ich verwende eine Architektur, bei der der Application Server NodeJS-Prozesse spawnt und mit denen via JSON kommuniziert, um den gleichen Code auf Client- und Serverseite verwenden zu können. Das heisst aber auch, dass jedes Posting, das auf dem Server gerendert wird, erst nach JSON konvertiert werden muss, dann vom NodJS-Prozess wieder deserialisiert werden muss, von Markdown nach HTML konvertiert werden muss, dann wieder nach JSON serialisiert werden muss und vom Application Server wieder deseriasiliert werden muss, um dann ins HTML geschrieben zu werden. Das kostet natürlich auch etwas.

Man könnte noch die Architektur ändern, so dass das serialisieren wegfällt, aber das kostet dann halt Maintenance. Ich müsste zwei Markdown-Parser pflegen, mit allen SELF-spezifischen Erweiterungen. Not gonna happen.

Ansonsten bin ich durchaus auch offen für mögliche Optimierungen ;-)

**Comment by ckruse** [comment]
Ja wtf. Ich denke, ich habe doch ein Problem finden können. [Ich habe das parallelisierte Prerendering mal abgeschaltet](https://github.com/ckruse/cforum_ex/commit/8b938dff8fa1f7c5123e4baf9bd4720732206f23), und tatsächlich liegt jetzt der worst case eher so bei 1000ms (927ms bei dem Gender-Thread).

Das überrascht mich doch. Das heisst, dass der Pool doch ausgehungert war. Faszinierend. Heute Abend mal noch etwas mit herumexperimentieren.

**Comment by Rolf-B** [comment]
Hypothese: Wenn dein AppServer und die Renderingfarm auf einer Dose laufen, und der AppServer 30 NodeJS Prozesse spawnt, die dann alle gleichzeitig loslaufen, sollte man für diesen Moment mal RAM und CPU-Last monitoren. Ggf. kommt läuft der virtuelle Speicher über, die Maschine kommt ins Swappen (bzw thrashen, wie wir das in den 80ern auf dem IBM Großrechner nannten), und weniger NodeJS Worker sind dann mehr.

Und: Du spawnst? Ist das effizient? Bedeutet das nicht, dass da jedesmal eine V8 Engine hochläuft und den JS Code JITten muss? Wenn man eine Renderingfarm baut, dann doch als mehrfach paralleler Microservice, mit durchlaufenden Servicenodes. Setzt natürlich einen Lastverteiler voraus; keine Ahnung was es da gibt oder ob Du das auch einfach aus dem Appserver heraus per Round Robin lösen kannst. Vorteil von Microservices ist auch, dass man sie im Zweifelsfall auf eine zweite Kiste legen kann, wenn dem Appserver die CPU Puste ausgeht.

Ich überlegte gerade, ob es sinnvoll sein kann, wenn die Thread-Renderer ihre Posting-Daten selbst aus der DB ziehen. Das sind dann mehr DB Connections und weniger Caching-Möglichkeiten in der Rendering-Farm, dafür weniger Daten, die via JSON an die Worker geschickt werden müssen. Aber vermutlich ist das ein architektonisches Gräuelstück...

**Comment by ckruse** [comment]
Nein, RAM und CPU sind kein Problem. Zumal auch nicht zum Rendering-Zeitpunkt 30 Prozesse gespawnt werden, sondern es handelt sich um einen Pool, wie ich bereits oben schrieb ;-) Der Pool hält nach Bedarf Prozesse bereit und wächst auf maximal 30 Worker.

Die Renderer diie Daten selber aus der DB holen zu lassen ist keine gute Idee. Das führt zu einer Menge doppelten Codes, es müssen ja nicht nur die Threads ausgelesen werden sondern auch die entsprechenden Flags gesetzt werden (gelesen, subscribed, bookmark, usw, pp).

**Comment by ckruse** [comment]
Ich mach das hier mal zu, ich denke, die Performance für große Threads ist inzwischen erträglich. Nicht gut, aber gut genug.
