### ISSUE TITLE
Verlinkung von URLs mit Klammern

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#119]
Bei der Verwendung des Verlinken-Buttons wird falsches Markdown generiert.

Nachvollziehen:

1. `Born to Run` ins Texteingabefeld schreiben und Text markieren
3. auf 🔗-Button (Link) clicken
4. im Dialogfenster den URL `https://de.wikipedia.org/wiki/Born_to_Run_(Lied)` eingeben, Formular absenden

Ergebnis: `[Born to Run](https://de.wikipedia.org/wiki/Born_to_Run_(Lied\))` – der Backslash vor der Klammer sorgt dafür, dass kein clickbarer Link generiert wird

erwartetes Ergebnis: `[Born to Run](https://de.wikipedia.org/wiki/Born_to_Run_(Lied))` ohne Backslash

**Comment by MatthiasApsel** [comment]
Ja, Markdown ist so schlau, die Paarigkeit der Klammern korrekt zu erkennen. 

befürchtetes Linkziel: `https://de.wikipedia.org/wiki/Born_to_Run_(Lied`
