### ISSUE TITLE
Automatisches Löschen von Benutzern, die nichts posten?

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#1195]
Ist das so? Muss ein Benutzer, auch wenn er bestätigt ist, etwas posten, um zu "überleben"? Oder was hat unsere(n) nichtbinäre(n) Kassierer(in) aus dem Forum verbannt?

Aus dem Audit:

Benutzer automatisch gelöscht Wiebke Knäpper (Medaillen keine) 29.12.2023 01:00
Benutzer bestätigt Wiebke Knäpper (Medaillen keine) 28.11.2023 22:28
Benutzer erstellt Wiebke Knäpper (Medaillen keine) 28.11.2023 22:27

**Comment by ckruse** [comment]
Er muss gelegentlich reinschauen. Posten ist nicht notwendig.

Das wurde implementiert, um der DSGVO genüge zu tun. Wir dürfen persönliche Daten nicht unbegrenzt speichern, sondern es braucht ein Löschkonzept. Und so werden User, die

- mindestens 5 Jahre das Forum nicht besucht haben
- oder 4 Jahre das Forum nicht besucht haben und in den letzten 5 Jahren weniger als 100 Nachrichten geschrieben haben
- oder 3 Jahre das Forum nicht besucht haben und in den letzten 5 Jahren weniger als 75 Nachrichten geschrieben haben
- oder 2 Jahre das Forum nicht besucht haben und in den letzten 5 Jahren weniger als 50 Nachrichten geschrieben haben
- oder 1 Jahr das Forum nicht besucht haben und in den letzten 5 Jahren weniger als 25 Nachrichten geschrieben haben

automatisch gelöscht.

**Comment by Rolf-B** [comment]
Und 1 Monat, wenn 0 Postings?

**Comment by ckruse** [comment]
Das oben waren die inaktiven User.

Es gibt noch die Spam-User. Wenn ein User sich anmeldet, das Forum nie besucht und nie etwas postet, gehe ich davon aus, dass es ein Spammer ist. Die werden nach 30 Tagen gelöscht.

User, die ihren Account innerhalb von 24 Stunden nicht bestätigen, werden auch gelöscht.

**Comment by Rolf-B** [comment]
Hm, im Fall vom Wiebke ist das mit dem Posten eher schwierig. 
Aber wenn es reicht, dass Wiebke regelmäßig reinschaut, dann kann man das wohl so lassen. 
Ich mach das hier dan zu

**Comment by ckruse** [comment]
**und nie besucht** -- regelmässig reinschauen reicht. Hab ich doch oben ausgeführt.

**Comment by Rolf-B** [comment]
Ja, hab ich auch so gemeint. Das sollte keine Rückfrage sein, nur ein Fazit.
