### ISSUE TITLE
Tags werden doppelt aufgeführt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#120]
https://forum.selfhtml.org/self/2019/sep/22/wie-bzw-kann-mir-jemand-helfen/1758100#m1758100

**Comment by ckruse** [comment]
Ist schon weg… ist die Archivierung für den Thread deaktiviert worden?

**Comment by MatthiasApsel** [comment]
Hmm. Weiß ich nicht. Dann muss ich mal drauf achten, wenn das wieder auftritt, ich vermute es wurde ein Tag und einer dessen Aliase ausgewählt, aber genau weiß ich es nicht mehr.

**Comment by ckruse** [comment]
Ich mach das hier mal zu weil nicht nachvollziehbar… wenn das nochmal auffällt bitte ein neues Issue aufmachen.
