### ISSUE TITLE
Trotz Standardberechtigung Lesen kann man im Metaforum Beiträge erstellen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#123]

**Comment by ckruse** [comment]
Das gilt für Admins und Moderatoren. Ja. Working as intended.

**Comment by MatthiasApsel** [comment]
Ich habe als anonymer einen Beitrag erstellt https://forum.selfhtml.org/meta/2019/oct/27/wetter/1759364?view_all=yes#m1759364
