### ISSUE TITLE
Mailto-Links werden nicht gerendert

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#124]
Im Posting werden mailto-Links nicht gerendert; in der Vorschau allerdings schon.

Siehe: [https://forum.selfhtml.org/self/2019/oct/25/dsgvo-und-reale-erlebnisse/1759375#m1759375](https://forum.selfhtml.org/self/2019/oct/25/dsgvo-und-reale-erlebnisse/1759375#m1759375)

**Comment by ckruse** [comment]
Kann ich nicht nachvollziehen. In dem verlinkten Posting gibt es keinen `mailto`-Link und bei mir lokal werden `mailto`-Links gerendert.

Kannst du das nochmal genauer prüfen und beschreiben?

**Comment by ckruse** [comment]
Ah. Es sind nicht `mailto`-Links das Problem, sondern dass `@selfhtml` als Mention erkannt wird.

**Comment by ckruse** [comment]
musst du maskieren. Mit `\\`.

**Comment by MatthiasApsel** [comment]
Es gab vor meinem Edit einen mailto-Link.

**Comment by campingrider** [comment]
Japp, Matthias hat da dazwischengefunkt. 

Ich sehe inzwischen, dass du auch editiert hast. Also ist das nicht-maskierte @ das Problem im Rendering; verstehe.

Dann besteht aber trotzdem das Problem, dass die Vorschau nicht das zeigt, was hinten rauskommt; ich verstehe jetzt auch warum.

Als ich das Posting getippt habe, hat der Mailto-Link ohne Maskierung funktioniert. Nach dem Abschicken nicht mehr.

Liegt natürlich daran, dass Mentions in der Vorschau noch nicht gerendert werden (richtig?), ist aber natürlich problematisch, weil man in der Vorschau den Eindruck hat, es funktioniert, und dann nach dem Absenden gehts nicht mehr.

Außerdem: In meiner uneditierten Variante wurde weder der mailto-Link noch die Mention durch den Renderer auch nicht aufgelöst, es war also auch nicht erkennbar, was da jetzt grade dazwischenfunkt und warum das ganze nicht funktioniert; die Mention wurde erst aufgelöst, als Matthias die Link-Syntax entfernt hatte.

Irgendwo passt also trotzdem was nicht; bzw. es ist für Benutzer schwierig, herauszufinden, was da zu maskieren ist und warum (der user muss eigentlich annehmen, dass Mentions eben nicht innerhalb von Links gesucht werden, denn mentions und links konkurrieren ja grundsätzlich in der Darstellung miteinander).
