### ISSUE TITLE
/subscriptions: Zeigt den Forennamen nicht an

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#13]
Da die Subscriptions-Anzeige forenübergreifend ist, sollte in den dort gezeigten Beiträge der Forenname angegeben sein. Ich wollte das mit CF4 vergleichen - gips da diese Anzeige noch gar nicht?

**Comment by ckruse** [comment]
Ja, sollte, dachte, das wäre schon so. Nein, gibt es noch nicht :-)

**Comment by ckruse** [comment]
das gleiche gilt auch für die Liste der als interessant markierten Beiträge
