### ISSUE TITLE
Man wird auch benachrichtigt, wenn der Thread nur gelöschte eigene Beiträge enthält

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#132]

**Comment by ckruse** [comment]
Ich verstehe nicht, was du meinst. Natürlich wirst du dann auch benachrichtigt über Aktivität in dem Thread, die Benachrichtigung geht allerdings halt vor der Löschung raus.

Oder was meinst du?

**Comment by MatthiasApsel** [comment]
Ich gehe davon aus, dass ich die Benachrichtigung nach der Löschung bekommen habe. Wahrscheinlich liegt es aber daran, das der Thread abonniert bleibt, wenn man mal eine Antwort geschrieben hat. Und da du nicht wissen kannst, wer aus welchem Grund einen Thread abonniert hat, ist es also works as disigned.

**Comment by ckruse** [comment]
Wie willst du denn eine Benachrichtigung für einen Thread bekommen, wenn er bereits gelöscht wurde? Da kann doch gar niemand mehr drauf antworten.

Ich bin verwirrt.

**Comment by MatthiasApsel** [comment]
Ich habe mich ungenau ausgedrückt. Der Thread existiert noch, aber mein Beitrag wurde gelöscht. Dann bekomme ich totzdem noch Benachrichtigungen für den Thread.

**Comment by ckruse** [comment]
Ach so! Ja ok, so macht das mehr Sinn. Und auch dein Grund das zu schließen ;-)
