### ISSUE TITLE
Thread-Ansicht kehrt automatisch zur Nested-Ansicht zurück

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#135]
Ich habe in einem Thread auf Thread-Ansicht umgeschaltet
URL: https://forum.selfhtml.org/self/2019/dec/17/php-deprecated-assigning-the-return-value-of-new-by-reference/1761817. 
Nach klick auf "Thread-Ansicht": URL um ?rm=thread#m1761817 erweitert.

Oben steht der Beitrag, darunter die Thread-Übersicht. Klicke ich auf einen Beitrag in der Thread-Übersicht, geht rm=thread verloren und ich bin wieder in der Nested-Ansicht. Soll das keine permanente Umschaltung sein?

**Comment by ckruse** [comment]
nein, das sollte keine permanente Umschaltung sein. Die nimmst du in der Konfiguration vor. Die Funktion ist als Ausnahme gedacht.

That said: ja, innerhalb des Baumes solltest du im gleichen Lese-Modus bleiben. Das ist ein Bug.
