### ISSUE TITLE
Hervorhebung von Benutzernamen funktioniert nicht mehr

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#138]
Neuerdings werden die Benutzernamen, die ich in den Benutzereinstellungen (Abschnitt Personalisierung) als hervorzuheben angegeben habe, nicht mehr farblich markiert. Auch die Hervorhebung des eigenen Benutzernamens funktioniert nicht mehr.

Ich habe mir mal den HTML-Code für einen hervorzuhebenden Benutzernamen in den Entwicklerwerkzeugen angeschaut (Forumshauptseite). Im Betreff eines OP sieht die relevante Struktur folgendermaßen aus: `div.details span.author span.registered-user [String.Benutzername]`. Eine Klasse, deren Namen auf die Hervorhebung schließen ließe, gibt es dort nicht.

**Comment by ckruse** [comment]
Das ist einer HTML-Änderung zum Oper gefallen… sorry. Fixed.
