### ISSUE TITLE
Bild wird nicht dargestellt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#139]
Wenn ich in https://forum.selfhtml.org/self/2020/jan/02/mathematik-zum-jahresanfang/1763188#m1763188 bei der unteren Grafik "?size=medium" ergänze, wird sie nicht angezeigt.

**Comment by ckruse** [comment]
Kann ich nicht nachvollziehen, geht hier…

**Comment by MatthiasApsel** [comment]
Aber das size=medium geht nach wie vor nicht. Auch in der Vorschau schon nicht. Nur im FF. im Edge geht es. Vielleicht ein Cache-Problem? Ich starte den Browser mal neu.

es gab einen edit-draft im local-storage. Den hab ich gelöscht. Jetzt geht es.
