### ISSUE TITLE
/forenname/archive - Überschrift sollte Forenname enthalten

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#14]
Aufgefallen in /spielwiese/archive: Ich vermisste im Archiv die Beiträge von 2018, und mir fiel nicht auf, dass ich in der Spielwiese war statt in Entwicklung oder Alles. 

Ob da nun "archivierte Beiträge - $forenname" oder "$forenname - archivierte Beiträge" steht, ist wurscht, aber wenn es das erstere ist, sollte es "Archivierte Beiträge - $forenname" sein :)

**Comment by ckruse** [comment]
über die Groß- und Kleinschreibung darfst du dich gerne mit @MatthiasApsel streiten ;P

**Comment by Rolf-B** [comment]
Hat der gesagt dass das a klein sein muss?
Ist doch eine Überschrift, also Satzanfang

**Comment by ckruse** [comment]
Es ist kein Satzanfang.

Aber falsch ist es trotzdem ;-) zumindest laut meiner Mutter (Deutsch-Lehrerin)

**Comment by MatthiasApsel** [comment]
Dem schließe ich mich an. Ich halte es für eine Unsitte, Überschriften grundsätzlich mit einem großen Buchstaben zu beginnen.

**Comment by ckruse** [comment]
Es ist keine Unsitte, sondern Rechtschreibung 😉

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Ja, sogar der Duden schreibt das so vor. Grmpf. "Wie Satzanfänge werden auch Überschriften und dergleichen behandelt."

**Comment by ckruse** [comment]
:rofl:
