### ISSUE TITLE
Antwortbenachrichtigung parst HTML im Betreff

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#140]
Mir werden für den Thread "Frage zu den Überschriften `<h1>` bis `<h6>`" im Browser kaputte Benachrichtigungen angezeigt [1]. Die HTML-Tags werden offensichtlich interpretiert, so dass das Wort "bis" als Überschrift gerendert wird.

![cforum-notice-reply](https://user-images.githubusercontent.com/1734660/73346611-75586680-4286-11ea-90bc-2be56b5431c8.png)

[1]: Hier – zumindest in der Vorschau – übrigens auch, wenn man die Tags nicht als Code auszeichnet. :-)

**Comment by ckruse** [comment]
Hm. Das scheint ein Bug in Upstream zu sein. Danke; werde in der Mittagspause ein Update veröffentlichen, dass das dann hoffentlich behebt: bei mir lokal kann ich es nicht nachstellen. Da habe ich allerdings auch schon eine neuere Version der Abhängigkeiten.

**Comment by ckruse** [comment]
Ach. Jetzt habe ich es verstanden.
