### ISSUE TITLE
Sprachauszeichnung: Sub-Tags werden ignoriert.

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#142]
In [diesem Posting](https://forum.selfhtml.org/self/2020/mar/05/designvorschlage-cookieleiste-automatisch-minimierend-schliessend/1766453#m1766453) hatte ich die Lautschrift mit `{:@de-fonipa}` gekennzeichnet. Im generierten HTML steht aber `lang="de"`, alles ab dem (ersten?) Bindestrich wird fälschlicherweise abgeschnitten. 🐞

BTW, die Langfassung `{:lang="de-fonipa"}` wird komplett ignoriert‽

**Comment by ckruse** [comment]
ja, die Langform wird nicht unterstützt.
