### ISSUE TITLE
Sortierung der Benachrichtigungen / Post

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum_ex#145]
Anscheinend hat die Sortierung der Benachrichtungen und / oder Post keine Einstellungsmöglichkeit ([„sortiere private Nachrichten…“](https://forum.selfhtml.org/users/3972/edit#user_settings_options_mail_thread_sort_ascending) scheint defekt oder anders gemeint zu sein) und es ist wird per default immer aufsteigend sortiert. Ich schlage daher vor, die Default-Sortierung zu ändern und absteigend zu sortieren, sodass immer die neuste Post oder Benachrichtigungen zuerst sichtbar sind. Eine Einstellmöglichkeit zum dauerhaften Ändern halte ich nicht für nötig.

**Comment by ckruse** [comment]
Hm. Die Einstellung sollte funktionieren. Mal schauen, was da schief läuft.

**Comment by ckruse** [comment]
Warum denkst du, dass „sortiere private Nachrichten“ nicht funktioniert? Hier geht es… Kann es sein, dass du die Sortierung angepasst hast indem du eine der Spalten angeklickt hast? In dem Fall gäbe es einen Cookie, der die Einstellung für diesen Browser speichert (müsste sowas wie `cforum_mail_controller-sort_col` bzw. `cforum_mail_controller-sort_dir` sein)

**Comment by JuliusPC** [comment]
Danke, bei den Mails wirkte die Einstellung nach dem Löschen der Cookies.

Auf die Benachrichtigungen wirkt sich die Einstellung aus den Einstellungen natürlich nicht aus. Die Cookies aber anscheinend auch nicht – Die werden zwar gesetzt, aber nur die URL-Parameter bestimmen die Sortierung. Sobald ich diese entferne, also <https://forum.selfhtml.org/notifications?sort=created_at&dir=desc> zu <https://forum.selfhtml.org/notifications> ist die Sortierung wieder die falsche.

Ich nahm an, dass nur eine Einstellung in den Einstellungen die Ansicht dauerhaft verändert, ein Klick auf die Sortierung das nur während der aktuellen Ansicht ändert (also bis ich die Ansicht der Benachrichtigungen durch Klick auf einen anderen Link oder Schließen des Tabs verlasse, jedoch natürlich nicht, wenn ich weitere Seiten der Benachrichtungen betrachte).

**Comment by ckruse** [comment]
Dass die Sortierung sich zurück setzt ist ein Bug. Das muss ich prüfen.

Dass die Sortierung in einem Cookie gespeichert wird war Wunsch der Community. Wobei wenn ich das gerade so sehe, das sollte man vielleicht in einen Session-Cookie ändern. Aktuell ist es ein Cookie mit 360 Tagen Gültigkeit…
