### ISSUE TITLE
Post: Löschung der Nachrichten bei einem Teilnehmer löscht Nachrichten bei beiden

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum_ex#146]
Ich denke nicht, dass das gewollt ist.

Fehlerbild: Matthias Scharwies hat bei sich das Postfach aufgeräumt „Unterhaltung löschen“ und schwupps waren auch bei mir alle Nachrichten verschwunden.

**Comment by ckruse** [comment]
Autsch…
