### ISSUE TITLE
Allgemeine Forenansicht - Name des Forums als Überschrift

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#15]
CF4 zeigt den Namen des anzeigten Forums als Überschrift an, CF5 nicht.
Absicht? Mein Fehler?

(1) CF4 Forum mit anzeigbaren Beiträgen

![Forenname](https://user-images.githubusercontent.com/34056213/56131113-e2fd0580-5f86-11e9-9c54-5137d20341dd.PNG)

(2) CF4 Forum in dem alles gelesen ist

![Forenname leer](https://user-images.githubusercontent.com/34056213/56131237-366f5380-5f87-11e9-8df4-b1a38cc31fde.PNG)

(3) CF5 Forum (zeige gelesene Beiträge Sicht)

![cf5-forenanzeiget](https://user-images.githubusercontent.com/34056213/56131351-7afaef00-5f87-11e9-8d76-5f65c07c0c92.PNG)

**Comment by ckruse** [comment]
Huh. Das ist ein Bug, der Titel und das `h1` sollten gesetzt sein.

Ah, ja, das ist ein Typo:

    def page_heading(action, assigns) when action in [:new, :create], do: page_title(action, assigns)

statt

    def page_heading(action, assigns), do: page_title(action, assigns)

 Ist im Source schon gefixed, ich lade das heute Abend hoch.
