### ISSUE TITLE
U+2060 als Trennzeichen bei @-Nennung

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#153]
https://forum.selfhtml.org/self/2020/jun/08/automatische-silbentrennung-beeinflussen/1771934#m1771934
Der Nutzername ist nicht verlinkt, obwohl es den Nutzer „Gunnar Bittersmann“ gibt. (Glaub ich jedenfalls. 😄)
Vermutlich wird nach „Gunnar Bittersmann<U+2060>s“ gesucht; das sollte nicht sein.
Neben U+2060 gibt es womöglich weitere Zeichen, wo noch nicht getrennt wird, aber getrennt werden sollte.

**Comment by Rolf-B** [comment]
Ich finde es wenig konstruktiv, spezielle Unicodezeichen einstreuen zu müssen, um einen Genitiv in einer Erwähnung nutzen zu können. Es ist zwar richtig, dass Da müsste es eine eigene Notation geben. Das Blöde ist, dass es im Englischen kein Problem ist: "@Rolf-B's posting was nonsense" und darum die @ Logik dieses Problem nicht vorsieht.

Zugegeben, hier in Github funktioniert das (Windows: Alt+8288 tippen): @Rolf-B⁠s Versuch ist gelungen. Aber man sieht es beim Editieren nicht. Ich würde lieber etwas ähnliches wie @[Rolf-B]s Versuch schreiben.

Hat eigentlich mal jemand getestet, was passiert, wenn die Userbase nicht präfixfrei ist, d.h. es gibt die User "Rolf" und "Rolf B" und jemand erwähnt Rolf B...

**Comment by ckruse** [comment]
es wird immer der längstmögliche Match gewählt, wobei nur ganze Wörter betrachtet werden. `@Rolf B` matcht also auf `Rolf B`, aber `@Rolf Bitte was?` matcht auf `Rolf`.
