### ISSUE TITLE
Reihenfolge der archivierten Beiträge ist verwirrend

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#157]
Die Beiträge sollten mMn nach dem Erstelldatum aufsteigend geordnet sein. Und zwar unabhängig von persönlichen Einstellungen, die wiederum nur für den aktuellen Threadbaum gelten sollten.

Im Juli 98 ist das derzeit so:

* Link auf Textmarke auf einer Seite im Frame Birgit Woskobojnik 29.07.98 09:18
* Willkommen im Forum! Stefan Muenz 26.07.98 13:19
* Bildbearbeitung und Bildkomprimierung Stefan Muenz 31.07.98 07:36

**Comment by ckruse** [comment]
Das sehe ich nicht so. Die Reihenfolge der archivierten Beiträge sollte sich nach der Benutzer-Einstellung richten. Dafür ist sie da…

**Comment by MatthiasApsel** [comment]
Der Kontext ist allerdings ein ganz anderer. Die letzten Beiträge der Threads sind, wenn ich mir die archivierten Beiträge anschaue (z.B. https://forum.selfhtml.org/all/1998/jul), ein denkbar schlechtes Sortierungskriterium, weil der letzte Beitrag ja auch irgendwo im Thread stehen kann. Im aktuellen Threadbaum dient diese Sortierung dazu, die aktiven Beiträge nach oben zu holen.
