### ISSUE TITLE
archivierte Beiträge sollten auf unread gesetzt sein

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#158]
Ich glaube, das war schon mal so ...

**Comment by ckruse** [comment]
Das ist immer noch so.

Obacht: das gilt nicht für die Gelesen-Markierung durch den Browser (`:visited`). Und galt auch nie.

**Comment by MatthiasApsel** [comment]
Ah. Daran könnte es liegen :-)
