### ISSUE TITLE
Es werden nicht alle archivierten Beiträge angezeigt (?)

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#159]
Sehr wahrscheinlich fehlen Beiträge. Etwa gibt es unter https://forum.selfhtml.org/all/2018/may?p=2 keine Beiträge vom Anfang des Monats. Es gibt immer nur zwei Seiten.

**Comment by ckruse** [comment]
Da hab ich mir aber auch einen Scheiss zusammenprogrammiert…
