### ISSUE TITLE
Popup für neues Posting bei abonnierten Threads erscheint mehrfach

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#189]
Es passiert nicht immer, aber wenn, dann regelrecht bildschirmfüllend. 10 Popupfenster untereinander sind durchaus keine Seltenheit. Aber ich kann nicht sagen, wie man das reproduziert. Hab's gerade aus einem Inkognitofenster als anonymer User versucht, brav nur 1 Popup. Hmpf. Aber vorhin ein ganzer Bildschirm voll.

**Comment by ckruse** [comment]
Und du bist sicher, dass da auch nicht bildschirmfüllend neue Nachrichten kamen? 😂

Hm, klingt merkwürdig…

**Comment by Rolf-B** [comment]
Nein, so wie das aussah bezog sich diese Meldung auf genau ein Posting. Ich versuch mal einen Screenshot zu machen wenn es wieder passiert, das ist nur schwierig weil die Meldungen ja nach einer Zeit verschwinden. Könntest Du einbauen, dass das Einblenden einer Popup-Meldung in der Konsole geloggt wird?

**Comment by ckruse** [comment]
Das war ein Scherz, hence the smiley :-)

Ja, das ist eine gute Idee. Mach ich heute Abend.

**Comment by ckruse** [comment]
Ist in Version 5.6.29 enthalten

**Comment by ckruse** [comment]
@Rolf-B schon so einen Fall gehabt?

**Comment by Rolf-B** [comment]
Söben

![image](https://user-images.githubusercontent.com/34056213/110250861-f4d26200-7f7d-11eb-9fa9-8e92ad7b4f4b.png)

**Comment by ckruse** [comment]
Aber in `/notifications` hast du nur eine?

**Comment by ckruse** [comment]
Mir ist zur Zeit nicht wirklich klar, wie das passieren kann. Das hier ist der Code, der die Notifications generiert:

~~~ elixir
    thread
    |> Cforum.Repo.preload([:forum])
    |> parent_messages(message)
    |> Subscriptions.list_subscriptions_for_messages()
    |> Stream.map(& &1.user)
    |> Stream.uniq_by(& &1.user_id)
    |> Stream.reject(fn user -> user.user_id == message.user_id end)
    |> Stream.reject(fn user -> Enum.find(already_notified, &(&1.user_id == user.user_id)) != nil end)
    |> Stream.filter(fn user -> may_view?(user, thread, message) end)
    |> Enum.each(fn user -> notify_user_message(user, thread, message) end)
~~~

Ich wüsste im Moment nicht, wie ich da doppelte Notifications generieren soll… 🧐 fehlgeschlagen und neu gestartet worden ist der Job auch nicht.

**Comment by Rolf-B** [comment]
> Aber in `/notifications` hast du nur eine?

Gar keine. Da ist meine letzte Benachrichtigung vom 21.02.

Dein Beispielcode - die Elixir/Erlang Syntax ist mir fremd. Was sehe ich da? Ist das eine Art "Filterkette", wo eine Enumeration durchgejagt wird und jede Zeile ist ein Teilfilter? In dem Fall würde ich auch sagen, dass da nichts doppeltes kommen sollte, aber könnte es sein, dass die ganze Kette mehrfach angestoßen wird?

**Comment by ckruse** [comment]
> Gar keine. Da ist meine letzte Benachrichtigung vom 21.02.

Ich hatte gehofft, dass du das noch siehst, bevor du die Nachricht aufmachst. Die Default-Einstellung ist, dass die Benachrichtigung gelöscht wird, sobald du die Nachricht besuchts. Das nächste mal gerne prüfen, wie die Benachrichtigungen in `/notifications` aussehen.

> Was sehe ich da?

Eine Pipeline im Sinne des Begriffs aus dem Bereich functional programming. Der Returnwert der Funktionsaufrufe wird immer weitergereicht an den nächsten Aufruf.

> aber könnte es sein, dass die ganze Kette mehrfach angestoßen wird?

Das kann vorkommen, wenn der Job fehlschlägt, in dem Fall würde er (bis zu 5 mal) neu gestartet. Aber dann hättest du auch mehrfach Benachrichtigungen in `/notifications`, deshalb meine Frage.

**Comment by ckruse** [comment]
Das halte ich für ausgeschlossen. Die Notifications kommen via Websocket rein, und werden relativ simpel dann in den DOM-Baum eingehängt. Da kann ich mir keine race condition vorstellen. Siehe <https://github.com/ckruse/cforum_ex/blob/master/assets/js/notifications/notification-updates.js#L56-L73>

**Comment by Rolf-B** [comment]
Ok, man muss mur meckern. Soeben wieder:

![image](https://user-images.githubusercontent.com/34056213/110798484-82fa6100-827a-11eb-9caa-81a17e7ec2d3.png)

In den Benachrichtigungen steht nur eine Zeile. Die kann aber nicht von Dir sein. Ausgeschlossen. So ein HTML schreibst Du nicht!

<table class="cf-default-table cf-notifications-table">
  <thead>
    <tr><th></th>
      <th> </th>
      <th><a class="cf-sortable" href="/notifications?sort=subject&amp;dir=asc">Betreff</a></th>
      <th><a class="cf-sortable sort-descending" href="/notifications?sort=created_at&amp;dir=asc">Erstellungszeitpunkt</a></th>
      <th> </th>
    </tr>
  </thead>

  <tbody>


      <tr id="1100363" class="notification "><td><input type="checkbox" value="1100363"></td>
        <td></td>
        <td>
<a href="/notifications/1100363">Auge hat einen neuen Beitrag geschrieben: „Website automatisch an Browserfenster anpaßen“</a>

        </td>
        <td>11.03.2021 14:59</td>
        <td>
<form action="/notifications/1100363" class="cf-inline-form" method="post"><input name="_method" type="hidden" value="delete"><input name="_csrf_token" type="hidden" value="BlIYBih8K2IaAQIBfREDKzZyEnlJI0Q1e8PCD2ZTMjhR8SUAZ4VApz1W"><button class="cf-destructive-index-btn" data-confirm="Sind Sie sicher?" type="submit">löschen</button></form>

        </td>
      </tr>

  </tbody>

</table>

**Comment by ckruse** [comment]
Tabellarische Daten gehören in Tabellen. 🤷‍♂️

Hast du das Fenster noch offen? Kannst du die anderen Objekte noch ausklappen?

Der Job ist auf jedenfall erfolgreich durchgelaufen…

**Comment by ckruse** [comment]
Also, ich kann es beim besten Willen nicht nachstellen. 😕 auch nicht, wenn ich von Hand die Notification rausschicke oder den Job von Hand starte.

**Comment by ckruse** [comment]
@Rolf-B hm - kann es sein, dass das passiert, wenn das Forum bereits einige Zeit offen war? Vielleicht hast du sogar den Rechner schlafen gelegt und öffnest ihn dann wieder? Oder sowas?

**Comment by ckruse** [comment]
Ok, ich denke, ich habe das Problem gefunden.

Jedesmal, wenn der Websocket disconnected wird, verbindet er sich automatisch neu. Das habe ich so eingestellt. Und jedesmal, wenn der Websocket sich verbindet, subscribe ich mich auf den entsprechenden Topics. Soweit, sogut.

Was ich allerdings nicht wusste: das Verhalten hat sich hier irgendwann mal geändert, und die Subscriptions werden bei einem Reconnect automatisch wiederhergestellt. Mein manuelles intervenieren hat also dazu geführt, dass bei jedem Reconnect das gleiche Topic ein weiteres mal abonniert wurde, und mit jedem weiteren Abo wurde die Nachricht dann entsprechend ein weiteres mal an den User ausgeliefert.

Ich habe da mal einen Toggle davorgebaut… das sollte helfen.

**Comment by Rolf-B** [comment]
Ich lese es und verstehe kein Wort. Websockets habe ich noch nicht verwendet, und um sie zu verwenden, braucht man ja auch einen speziellen Server. Ein normaler Apache oder IIS tut das nicht. Da habe ich bisher immer einen Bogen drumherum gemacht.

**Comment by Rolf-B** [comment]
Okay, Habe es mit Sperren und Energiesparen versucht. Mit "Internet Trennen und Wiederverbinden" nicht, meine Frau guckt via IP-TV fern :) Bisher alles im grünen Bereich.

**Comment by ckruse** [comment]
Das management summary ist: die Websocket-Bibliothek, die ich verwende, hat ihr Verhalten im Laufe der Zeit mal verändert. Das hat dazu geführt, dass der Socket mehrfach für Benachrichtigungen eingetragen wurde und deshalb solche Benachrichtigungen mehrfach bekommen hat.

**Comment by Rolf-B** [comment]
Ich brauche eine management summary?! - Jetzt bin ich beleidigt 😉 

Ok, wenn da eine Lib zwischen war, dann verstehe ich es. Weil - ich hatte bisher nichts davon gehört, dass Websockets im Protokoll sowas wie Subscriptions gehabt hätten.

**Comment by ckruse** [comment]
😜

Ich verwende das [Phoenix Framework](https://phoenixframework.org/). Das bietet eine ziemlich gute Websocket-Integration. Man kann Channels beitreten, und innerhalb dieser Channels kann man auf Events subscriben.

**Comment by ckruse** [comment]
@Rolf-B irgendwas neues?

**Comment by Rolf-B** [comment]
Bisher ist nichts mehr aufgefallen.

**Comment by ckruse** [comment]
Ich gehe jetzt mal davon aus, dass das Problem behoben ist und mache hier mal zu. Wenn es nochmal wieder auftritt, meld dich einfach nochmal.
