### ISSUE TITLE
Posting-Editor wird bei Browser-"Zurück" nicht ausgeblendet und Draft bleibt stehen

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#20]
Postings fanden in der Spielwiese statt. Möglicherweise liegt hier eine Ursache für hängen gebliebene Drafts, aber da muss mehr sein - einmal habe ich einen Draft ganz kurz verschwinden und neue auftauchen sehen.

Aufruf Root-Posting des Thread (URL ist danach ...entwurf-test-neuer-thread/329#329)

Klicke auf Antwort 1 (#330). URL ist jetzt entwurf-test-neuer-thread/330#m330
Klicke auf Antwort 2 (#331). URL ist jetzt entwurf-test-neuer-thread/331#m331
Klicke auf Antwort 3 (#332). URL ist jetzt entwurf-test-neuer-thread/332#m332

Auf Antwort 3 Hover über "Antwort verfassen:" zeigt entwurf-test-neuer-thread/332/new

Klick auf "Antwort verfassen" reagiert per Javascript. URL bleibt entwurf-test-neuer-thread/332#m332, aber Antwort-Editor geht auf. Finde ich falsch, hier hätte ein push auf die History mit 332/new erfolgen müssen. 

Schreibe "Test-Antwort". Es entsteht ein Draft mit entwurf-test-neuer-thread/332/new

Klicke Browser-Button "Zurück". URL wechselt zu entwurf-test-neuer-thread/331#m331 und #332 klappt sich ein, aber der Antwort-Editor zu 332 bleibt offen und der Draft wird nicht gelöscht! Ein history-push hätte das vermutlich verhindert.

Mehrfach "zurück" bis zur Spielwiese-Ansicht; Draft ist geblieben.

**Comment by Rolf-B** [comment]
Der "vergessene" Timer würde das Wiederauftauchen des Entwurfs erklären. 

Ich mache einen neuen Testzyklus, wenn ich Zeit habe (Ostern = Familie)

**Comment by ckruse** [comment]
Ja, hier auch- deshalb hab ich die letzten Tage auch nichts von mir hören lassen 😉 frohe Ostern!

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by Rolf-B** [comment]
Ok, Drafts scheinen nach Save jetzt zu verschwinden, aber der Back-Button springt immer noch eins zu weit. Ich bin in der Thread-Ansicht (z.B. https://cftest.wwwtech.de/spielwiese/2019/apr/13/ist-ein-foo-besser-als-ein-bar/304#m304), drücke Antworten, dann den Zurück-Button des Browsers. Und ich bin hier: https://cftest.wwwtech.de/spielwiese?srt=yes

Das ist eins zu viel.

Wie schon gesagt: Da dürfte ein push von 304/new (also das, was man beim Hovern über dem Antwortbutton sieht) in die History fehlen.

**Comment by ckruse** [comment]
Ich habe dir erstmal nicht widersprochen. Ich bin mir nur noch nicht im Klaren darüber, ob ich das auch so sehe. Sonst hätte ich mich schon geäußert oder eine Diskussion gesucht 😉

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by Rolf-B** [comment]
Sagen wir mal so: Das Verhalten sollte bei ein- und ausgeschaltetem JS vergleichbar sein.

Wenn ich JavaScript ausschalte und einen Beitrag beantworte, lande ich auf einer /new Seite. Klicke ich den "Zurück" Button, gelange ich zum Posting zurück. 

Wenn ich JavaScript einschalte und einen Beitrag beantworte, macht er das inline und ich bleibe auf der nnn#nnn Seite (nnn=Beitrags-ID). Klicke ich den "Zurück" Button, gelange ich in die Threadübersicht des Forums.

Vermutlich fällt es eh nur versicherungsgeschädigten Programmieren wie mir auf, deren Tester ein Pfund Korinthen zum Frühstück verputzen, um während des Tages genug davon zum Kacken zu haben.

**Comment by ckruse** [comment]
Ich habe durchaus verstanden, was dein Anliegen ist :-) aber ich war mir noch nicht sicher, ob ich das auch so sehe.

Ich hatte aber inzwischen Zeit darüber nachzudenken und finde, dass du Recht hast. Das Formular sollte sich in der Adresszeile wiederfinden.

**Comment by ckruse** [comment]
Ist implementiert mit 0d0ba0ff1e6b0aec41e72fb9204a96ffb2b8e3a8
