### ISSUE TITLE
Popup-Position der Eingabehilfen ist bei Pfeilnavigation falsch

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#21]
Wenn man mit den Pfeiltasten den Cursor im Beitrag-Editor herumlaufen lässt und den Cursor hinter einen String positioniert, der ein Popup mit Eingabehilfen triggert (Minus, Anführungszeichen, drei Punkte), dann wird die Position des Popup basierend auf der Cursorposition vor Ausführung der Pfeiltaste berechnet.

Das stört insbesondere dann, wenn man die ArrowDown Taste gedrückt hat, weil das Popup dann die aktuelle Zeile überlagert.

**Comment by ckruse** [comment]
Nur um Missverständnisse zu vermeiden: ich bin dran… es läuft im Grunde darauf hinaus, diese Autocomplete-Komponente wegzuwerfen und entweder selber eine zu schreiben oder eine andere, alternative zu wählen.

**Comment by ckruse** [comment]
Sollte mit der neuen Komponente gefixed sein
