### ISSUE TITLE
Menü geht nicht mit „grauem“ Stylesheet

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#211]
Beim Umschalten auf Grau ist im Stylesheet was verlorengegangen? Das Aufklapp-Menü in *z*-Richtung zu weit hinten und wird überdeckt:
![Bildschirmfoto 2021-03-12 um 05 03 33](https://user-images.githubusercontent.com/409844/110890720-dc9d7280-82f0-11eb-9fcc-87791104cb08.png)

**Comment by ckruse** [comment]
Faszinierend. Das scheint mir ein Rendering-Bug zu sein.

**Comment by ckruse** [comment]
Man muss nur den grayscale-Filter ausschalten und schon ist das Menü wieder wie vorher. Auch die Breite des Menüs ändert sich.

Ich glaub echt, dass das ein Rendering-Bug ist.

**Comment by Rolf-B** [comment]
Ich habe eine Hypothese, aber da fehlt noch was. 

Es ist - zumindest teilweise - kein Browser-Bug, sondern einer, der durch das globale Setzen von filter:... im Stylesheet entsteht. Die filter-Eigenschaft bewirkt nämlich, dass ein Element einen stacking context bekommt ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). D.h. die Seite hat durch den global gesetzten Filter auf einmal eine Menge Stacking-Kontexte mehr.  Und ohne z-index liegen später erzeugte Stacking-Kontexte über früher erzeugten

Die Elemente header.cf-page-header und main sind Geschwisterknoten, main kommt später, deswegen liegt es im Stacking über dem header und die Kinder des Headers können sich nicht über das main Element erheben. Das Gleiche gilt für nav.quicklinks und nav.subnav innerhalb des Headers. Ohne den Filter lagen header und main im gleichen Stacking-Kontext und das Dropdown-Menü machte wegen position:absolute einen neuen auf. Der dann oberhalb des Stacking-Kontextes liegt, in dem sich header und main befinden. Die filter-Eigenschaft verändert das.

Während man das Problem **innerhalb** des Headers aber mit einem z-index:100 auf nav.quicklinks behoben bekommt, gelingt es durch eine z-index Angabe bei header.cf-page-header nicht. Der Header bleibt unterhalb des main. Sollte er aber nicht. Irgendwas an den Stacking Contexts habe ich wohl immer noch nicht verstanden. Oder da ist nun wirklich ein Browser Bug.

Quick Fix wäre vermutlich, die Filter-Eigenschaft dosierter zu setzen und im Zweifelsfall etwas Farbe zuzulassen.

**Comment by Rolf-B** [comment]
Uff, nach dem drölften Edit sollte es nun aber stimmen.

**Comment by Rolf-B** [comment]
Der Graufilter verhindert übrigens auch, dass man neuen Beiträge erkennt. Vielleicht sollte man ihn nur auf den Headerbereich anwenden.

**Comment by ckruse** [comment]
Danke für deine Analyse, das ist in der Tat sehr hilfreich. Ich werde mir das heute Abend genauer anschauen.

Bezüglich „nur auf den Header-Bereich:“ das bleibt jetzt ein paar Tage so. In der Zeit müssen die User halt damit leben, dass ein paar Features weniger gut funktionieren.

**Comment by auge8472** [comment]
Der Vollständigkeit halber:

- Beim erstellen oder bearbeiten eines Postings funktioniert (zumindest) der Button für einen Link nicht. Statt den modalen Dialog für die Eingabe der URL und des Linktextes zu öffnen, springt der Viewport beim ersten klicken auf die Höhe des Absendebuttons. Beim zweiten Klickversuch auf den Button passiert überhaupt nichts.
- Das Auswahlfenster für Emojis wird hinter dem Texteingabefeld für das Posting geöffnet, reagiert aber auf Klick- und Eingabeversuche, soweit sie auf der erreichbaren Fläche erfolgen.

Erlebt im Firefox 86.0 unter Ubuntu 18.04

**Comment by Rolf-B** [comment]
Ich glaube, ich habe eine relativ einfache Lösung. Die kann man in seinem Custom CSS ausprobieren.

```
*, *::after, *::before {    /* Default Wiederherstellen, wenn man das in sein Custom-CSS eintragen will */
    filter: none;
}

.cf-page-header, .cf-personallinks, .cf-top-bar, #content {
    filter: grayscale(1);
}

#content .cf-message-header:not(.visited) a::before {
   content: "▶ ";
}
```

Damit ist der gesamte Kopfbereich grau. Der Foreninhalt ist auch grau, und neue Beiträge bekommen einen Pfeil (der zumindest bei mir hier in Github weiß auf blau ist, im Forum aber schwarz auf transparent). Ohne den Pfeil tut man sich schwer, neue Beiträge zu finden.

Das behebt, hoffe ich, alle Stacking-Probleme. Ich habe das jetzt zusammen mit einer unset-Regel

**Comment by ckruse** [comment]
Hehe, ich bin gerade an einer sehr ähnlichen Regel :-) 👍

**Comment by Rolf-B** [comment]
Die .message-header Regel braucht noch ein > vor dem a::before, sonst erscheint über dem Inhalt einer neuen Message eine ganze Pfeilewolke...

**Comment by ckruse** [comment]
Ja, hatte ich schon gesehen. Sobald <https://github.com/ckruse/cforum_ex/runs/2095723164> durch ist, sollten die Änderungen live sein.

**Comment by Rolf-B** [comment]
Hehe, z-index:1000 am Header legt ihn über das ReactModalPortal. Ich hatte aus gutem Grund den z-index da weggelassen. Aber jetzt sehe ich: den z-index am header braucht man doch, wenn das Foren-Menü so lang ist, dass es in den #content Bereich hineinragt.  

Also am header z-index 1 und am ReactModalPortal z-index 2.

**Comment by ckruse** [comment]
Und ich hatte z-index:1000 extra reingenommen, weil ich gesehen hatte, dass man es braucht – hatte aber dafür nicht an das Overlay gedacht 🤣

Fixed.

**Comment by Rolf-B** [comment]
Ich wollte schon ein neues Issue aufmachen, weil die Menüs wieder nicht stimmten. Und dann merkte ich: du hattest die Graustufen deaktiviert, und mein Custom-CSS, dass den grayscale-Filter auf 70% reduziert hatte, passte nun nicht mehr. Autsch.

Ich hab ihn also rausgenommen und einen Farbschock bekommen. MANN ist das Forum bunt, wenn man es eine Woche lang grau gesehen hat.

**Comment by ckruse** [comment]
Hihi
