### ISSUE TITLE
Alte Links in Blog funktionieren nicht mehr

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#223]
Ich bin im Wiki gerade auf diesen Link gestoßen:

`https://blog.selfhtml.org/2015/07/15/graceful-degradation-vs-progressive-enhancement/`

Der funktioniert nicht, weil der Blog-Eintrag ein `1-` vor den Namen bekommen hat. Ich dachte zuerst, da wär noch mehr, bin aber gerade verwirrt wo ich mich selbst in den Fuß schieße, daher editiere ich das erstmal wieder weg. Followup kommt

**Comment by Rolf-B** [comment]
Ok, der Link aus dem Blog-Archiv geht auf die forum-Subdomain und hat noch ein weblog im Pfad. Wenn `weblog` dabei ist, muss auch die Thread-ID hinten dran stehen. Aber das ist bei Alt-Links auf den Blog ja nicht der Fall.

Bleibt die Frage, weshalb da ein `1-` in den Titel geraten ist, der den Link schreddert. Ich ändere das jetzt erstmal im Wiki; sollte der Blog-Eintrag zurückbenannt werden, bitte Nachricht, ich drehe das Wiki dann wieder zurück.

**Comment by ckruse** [comment]
Bitte immer die Quelle angeben. So kann ich nichts dazu sagen. Und nicht einfach ändern, ich muss mir angucken können, was du meinst. Deine Beschreibung allein ist leider zu wirr, als dass ich verstehen könnte, was du meinst.

**Comment by ckruse** [comment]
Argh. In der Mail steht was ganz anderes als du hier geschrieben hast. Du verwirrst mich! 😂

Ich verstehe jetzt, was du von mir möchtest.

Ja, bei IIRC zwei Blog-Beiträgen hat sich die URL  geändert. Das liess sich nicht vermeiden, weil die URL bereits vergeben war.
