### ISSUE TITLE
Moderationsmeldung wird nicht angezeigt

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#224]
Es gibt wohl eine Moderationsmeldung zu diesem Kommentar im Blog-Eintrag zu Mattias Apsel:

<https://forum.selfhtml.org/weblog/2021/mar/11/besturzt-und-fassungslos-matthias-apsel-ist-gestorben/1785955>

Sie ist offen, Matthias Scharwies sieht sie, die anderen sehen sie scheinbar auch, aber ich sehe sie nicht. Ich habe 0 offene Meldungen. Ist das ein Berechtigungsproblem? Oder eine Macke bei Mod-Meldungen zu Blog-Einträgen?

**Comment by Rolf-B** [comment]
Update: JürgenB sieht sie auch nicht

**Comment by auge8472** [comment]
Auch ich sehe die Meldung nicht. Nicht in den unbearbeiteten und nicht in den erledigten Fällen.

**Comment by Rolf-B** [comment]
Martin auch nicht. Sind Blog-Modmeldungen nur für Admins sichtbar?

**Comment by ckruse** [comment]
Moderations-Queue-Meldungen sind nur für Personen sichtbar, die Mod-Zugriff auf das Forum haben, in dem das Posting ist, das gemeldet wurde.

Im Weblog waren normale Moderatoren keine Mods. Ich hab das mal geändert, Matthias wollte das damals eigentlich so haben, hat dann aber wohl vergessen die Gruppenberechtigungen anzupassen.
