### ISSUE TITLE
Anhängen von Bildern - welche Regeln gelten?

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#225]
Henry ist am moppern weil er mit dem Anhängen von Bildern Probleme hat.

Ich wollte testen: 3x ein das gleiche kleine JPG (< 10KB) anhängen - geht. Das PNG, aus dem dieses JPG entstanden ist, geht nicht. Uups, es ist etwas schiefgegangen.

Was darf man anhängen, was nicht? Welche Regeln werden da be-Uups-t?

FM in der Console oder als HTTP-Errors gibt's nicht wirklich. Ich sehe nur, dass der POST auf images/api/v1 einen HTTP 200 mit {"status": "error"} in der Response liefert.

**Comment by ckruse** [comment]
Auch wenn mir Henrys meckern herzlich egal ist: hört sich nach Datei-Größe an. Muss ich mir aber näher anschauen. Hast du mir eine Beispiel-Datei?

**Comment by Rolf-B** [comment]
Ich habe die Bilddatei, die das Problem verusacht, direkt hier angehängt, dann wieder downgeloadet (um Reproduzierbarkeit sicherzustellen) und diesen Download als Bild in ein Forenposting gehängt. FUNKTIONIERT.

Die Originaldatei funktioniert nicht. Darum hier ein ZIP mit den beiden Bildern. Ich habe es downgeloaded und entpackt, damit ist es reproduzierbar. Das PNG geht nicht, das JPG geht.

[DisableCache.zip](https://github.com/ckruse/cforum_ex/files/6169591/DisableCache.zip)

Ich würde daher annehmen, dass das PNG irgendwelche Eigenschaften hat, die das Forum stören. An der Größe kann es nicht liegen, das gleich große JPG funktioniert ja, auch mehrfach in ein Posting.

**Comment by ckruse** [comment]
Danke, sehr hilfreich… ich schaus mir in der Mittagspause oder heute Abend an

**Comment by Rolf-B** [comment]
Update. Es scheint die Schreibweise der Extension zu sein. jpg geht, png geht, JPG geht schief, PNG auch.

**Comment by ckruse** [comment]
[Deploy läuft…](https://github.com/ckruse/cforum_ex/runs/2147645614)
