### ISSUE TITLE
Einfügen von Bildern mit Copy+Paste

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#228]
Du bist einfach zu schnell 😄 

Ich habe im Win10 Snipping-Tool ein Bild geschnappt und kopiert. Dieses füge ich mit Strg+V in ein Posting ein.

Geht alles prima, nur das Bild wird nicht angezeigt. Ich muss ?size=medium aus der Bild-URL entfernen, dann klappt es. Ist egal ob das Bild klein ist (also size=medium irrelevant ist) oder groß.

Per Default wird ja in den Beitrag (bleistiftsweise) dies hier gesetzt (wenn man die Beschreibungsfelder leer lässt):
`[![](/images/b9983976-88a1-11eb-8cfb-b42e9947ef30.png?size=medium)](/images/b9983976-88a1-11eb-8cfb-b42e9947ef30.png)`

Die Link-Einbettung kann man entfernen, also  
`![](/images/b9983976-88a1-11eb-8cfb-b42e9947ef30.png?size=medium)`

Kein Bild in der Anzeige. Aber sobald hinter size nicht mehr medium steht, ist alles wieder gut. Das passiert aber nur bei Dateien die mit Copy+Paste oder Drag+Drop eingefügt wurden, Martins Bild vom DSL Router kommt, obwohl size=medium dranhängt.

**Comment by ckruse** [comment]
das einfügen von Bildern mit C&P hätte ich nie implementieren sollen… das ist auf OS- und Browser-Seite dermaßen kaputt, gruselig. Seufz.

**Comment by ckruse** [comment]
Hm. Kann ich nicht nachvollziehen. Hab aber auch kein Windows.

**Comment by ckruse** [comment]
Tut mir leid, aber das kann ich nicht nachstellen. Bist du dir sicher, dass du das richtig beobachtet hast? Denn <https://forum.selfhtml.org/images/b9983976-88a1-11eb-8cfb-b42e9947ef30.png?size=medium> ist bei mir abrufbar.

**Comment by Rolf-B** [comment]
Spannend. Gerade auf diesen Link geklickt - leeres Fenster. "medium" in "medixum" geändert und ENTER - Bild kommt.
\*screeeeech\* - Vollbremsung
Nach F5 kommt das Bild nun. Jedesmal. Offenbar hatte mein Browser die leere Antwort gecached. HÄ? Ist das ein Timing-Problem - wenn ich das mit C+P oder D+D eingefügte Bild einfüge, läuft bei Dir im Hintergrund noch eine Aufbereitung, und mein Chrome ruft es bei der Rückkehr ins Forum zu früh ab und hat dann ein leeres Bild im Cache? Jetzt passiert es auch nicht mehr. Ist es eine Frage der Serverbelastung, tagsüber?

**Comment by ckruse** [comment]
Eigentlich nicht. Solange das Medium-Bild nicht existiert, wird das Original-Bild ausgeliefert. Im schlimmsten Fall bekommst du also das Original-Bild und hast das dann erstmal 30 Tage im Cache.

**Comment by ckruse** [comment]
Hm, eine potentielle race condition gibt es vielleicht doch. Es könnte sein, dass du genau zu dem Zeitpunkt das Bild angefragt hast, als die Datei geschrieben wurde. Also z.B. `open` durch convert, `stat` durch mich, Auslieferung der unvollständigen Datei.
