### ISSUE TITLE
Gelöschter, aber ungelesener Beitrag wird in der Non-Admin Ansicht angezeigt?

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#229]
Ich habe heute schweren Schnupfen. Issue - Issue - Issue - Gesundheit 😉 

Ich rufe <https://forum.selfhtml.org/weblog?srt=yes> auf, und sehe den Beitrag #1785891 von friedrich. Der wird als ungelesen hervorgehoben, aber als gelöscht durchgestrichen. view_all=yes ist **nicht** in der URL.

Den gelöschten Beitrag #1785955 von localhorst, den ich gelesen hatte, sehe ich erwartungsgemäß nicht.

Soll das so sein oder zeigt mir srt=yes da Dinge, die ich nur in der Admin-Ansicht (view_all=yes) sehen sollte?

**Comment by ckruse** [comment]
Ich verstehe das Problem nicht.

Ich gehe jetzt mal davon aus, dass du „verstecke gelesene Threads“ aktiviert hast, ansonsten macht `?srt=yes` wenig Sinn.

In `/weblog` wird dir dann der Thread ausgeblendet, weil kein ungelesenes, ungelöschstes Posting existiert. In `/weblog?srt=yes` wird der Thread eingeblendet, weil er nur gelesene oder gelöschte Postings enthält.

Localhosts Beitrag wird dir nicht angezeigt, weil er ohne öffentliche Lösch-Begründung gelöscht wurde. Friedrichs Beitrag wird dir angezeigt, weil er mit Löschbegründung gelöscht wurde.

Friedrichs Beitrag wird dir als ungelesen markiert, weil du ihn noch nicht gelesen hast.

Ist es für dich nicht so? Oder habe ich etwas verpasst?

**Comment by Rolf-B** [comment]
> Ich verstehe das Problem nicht.

Oder ich verstehe das Forum nicht und sehe darum Probleme, wo keine sind 😉 

> „verstecke gelesene Threads“ aktiviert

Hab ich. Ohne die Angabe srt=yes sehe ich den Thread nicht. Mit der Angabe sehe ich den Thread, offenbar deshalb, weil er einen ungelesenen, aber gelöschten Beitrag enthält. Was ich für falsch halte. &lt;meinung>Ein gelöschter Beitrag ist gelöscht. Dass in einem Thread ein Beitrag gelöscht wurde, ohne dass ich ihn gesehen habe, ist egal. Ich soll, muss und will den nicht sehen. Er wurde gelöscht. Wenn ich gelöschte Dinge sehen will, muss ich Adminrechte haben und die Admin-Ansicht aktivieren.&lt;/meinung>

Dass sich die Sichtbarkeit eines gelöschten Beitrags danach richtet, ob er mit oder ohne Begründung gelöscht wurde, war mir unbekannt. Sind Löschungen ohne Begründung den Foren-Admins vorbehalten und damit "Löschungen höheren Ranges"? Das soll keine Polemik sein, falls Du das so auffasst - einfach nur die Frage nach dem Löschkonzept.

**Comment by ckruse** [comment]
> Ohne die Angabe srt=yes sehe ich den Thread nicht.

Also so, wie es mit der Konfigurationsoption vorgesehen ist.

> Mit der Angabe sehe ich den Thread, offenbar deshalb, weil er einen ungelesenen, aber gelöschten Beitrag enthält.

???? Nein? Bei `srt=yes` siehst du den Thread, weil du gesagt hast, du willst jetzt die gelesen Threads sehen. `srt` steht für „show read threads“ – zeige gelesene Threads. Working as intended?

Ich will dich nicht ärgern, ich verstehe nur wirklich nicht, warum du hier einen Bug siehst.

> Sind Löschungen ohne Begründung den Foren-Admins vorbehalten und damit "Löschungen höheren Ranges"?

Es gibt zwei Arten der Löschung: Löschung mit öffentlicher Begründung, die können alle Mods sehen. Und Löschungen ohne öffentliche Begründund, dann ist das Posting schlicht nicht sichtbar.

**Comment by Rolf-B** [comment]
Hm. Leicht falsch formuliert von mir. Der Bug ist nicht der Thread. Dass ich den bei srt=yes sehe, ist ok, das hab ich bestellt. Der Bug ist der gelöschte Beitrag, den ich im Thread sehe. Den hab ich nicht bestellt. Der Löschgrund ist - meine ich - völlig egal. Das meinte ich mit gelöscht ist gelöscht und soll nur in der Admin-Ansicht sichtbar sein. 

Es gibt ja 4 Kombis aus srt=no/yes und view_all=no/yes. Aber die sollten sich so verstehen lassen:

srt=no, view_all=no: Ich sehe nur ungelöschte Beiträge. Threads, in denen alle Beiträge, die ich sehen kann, gelesen sind, werden ausgeblendet.
srt=no, view_all=yes: Ich sehe alle Beiträge. Threads, in denen alle Beiträge gelesen sind, werden ausgeblendet.
srt=yes, view_all=no: Ich sehe nur ungelöschte Beiträge. Threads, in denen ich mindestens einen Beitrag sehen kann, sind sichtbar.
srt=yes, view_all=yes: Ich sehe alle Beiträge und alle Threads.

Oder anders formuliert, erfolgt die Ermittlung in zwei Schritten:

Schritt 1:
view_all=no: verwende eine Forensicht, in der gelöschte Beiträge nicht existieren
view_all=yes: verwende eine Forensicht, in der gelöschte Beiträge existieren

Schritt 2:
srt=no: In der verwendeten Forensicht bekomme ich die Threads zu sehen, die einen ungelesen Beitrag enthalten
srt=yes: In der verwendeten Forensicht bekomme ich alle Threads zu sehen

Wobei der Zustart des srt-Flags vermutlich vom Schalter "verstecke vollständig gelesene Threads" abhängt und vom URL-Parm überschrieben werden kann.

Oder denke ich zu simpel?

**Comment by ckruse** [comment]
Nun, dann haben wir es hier mit einer Meinungsdifferenz zu tun. Dass mit Löschgrund gelöschte Beiträge angezeigt werden und bei Aufruf der Löschgrund zu ehen ist, ist Teil einer Transparenz-Initiative gewesen und durchaus so beabsichtigt.

**Comment by auge8472** [comment]
Schön wäre es, wenn ein (in der Einzelansicht) aufgerufenes, gelöschtes Posting als gelesen gewertet wird. Threads mit gelöschten aber der Transparenz wegen "angezeigter" Postings klappen nicht zusammen, weil das Posting trotz Aufruf ungelesen bleibt.

Mit dem Problem kann man umgehen (den Thread über den entsprechenden Button als gelesen markieren), schöner wäre es aber, wenn man ohne diese zusätzliche Aktion auskäme.

**Comment by ckruse** [comment]
Wenn man „gelesene Threads zusammenklappen“ aktiviert hat sollten eigentlich gelöschte Postings nicht dazu führen, dass der Thread ausgeklappt wird… wenn das der Fall ist, dann ist das ein Bug.

**Comment by ckruse** [comment]
So, nach einer Woche beim AG vor Ort mit 06:30-21:00 bzw 23:00-Schichten (User nerven 🤣) habe ich gerade versucht dieses Problem nachzustellen. Aber bei mir wird ein Thread mit ungelesenen gelöschten Postings zusammen geklappt?

**Comment by Rolf-B** [comment]
Reden wir hier über ein Thema? "Zusammenklappen" und "Überhaupt als Thread anzeigen" - sind das nicht zwei Dinge?

**Comment by ckruse** [comment]
dass es angezeigt wird, daran gibts erstmal nichts zu rütteln. Das ist so gewollt, deshalb gibt es überhaupt erst die zwei Löschungsarten.

Die Rückfrage mit dem „zusammenklappen“ war eine Reaktion auf @auge8472 Wunsch, dass mit Begründung gelöschte Postings sich verhalten wie gelesene Postings. Das sollte der Fall sein, und bei mir ist das auch der Fall. Daher meine Rückfrage.

**Comment by auge8472** [comment]
Sorry, dass ich so lange nicht geantwortet habe.

Wenn ein Posting, zum Beispiel wegen Spams, gelöscht wurde, wird es mit seinen Metadaten der Transparenz wegen immer noch im Threadbaum angezeigt. Wenn ich es aufrufe, um den Löschgrund zu erfahren, wird es aber nicht als gelesen gezählt. Dass das nicht der Fall ist, wenn ich mir seinen ursprünglichen Inhalt in der Administratoransicht anzeigen lasse, kann ich noch nachvollziehen, aber dass der Aufruf in der Normalansicht nicht dazu führt, dass das Posting als gelesen gewertet wird, verwirrt mich immer wieder.

Wenn ich alle tatsächlich vorhandenen Postings gelesen *und* das gelöschte Posting des Löschgrunds wegen aufgerufen habe, erwarte ich halt, dass der Thread zugeklappt wird. Wird er aber nicht und die farbliche Markierung des Betreffs des gelöschten Postings als nicht gelesen sagt mir auch warum.. Wenn ich das bemerke, muss ich den Thread ja nur über den entsprechenden Button am Eröffnungsposting als gelesen markieren. Dabei wird dann auch das gelöschte Posting als gelesen markiert und als Folge dessen der Thread zusammengeklappt. Mit der (mMn) Unstimmigkeit lässt sich also leben, auch wenn es anders schöner wäre.

Dummerweise lässt sich das gerade jetzt nicht an einem vorhandenen Beispiel zeigen. Und extra Müll zu erzeugen scheue ich mich.

**Comment by ckruse** [comment]
@auge8472 Alles gut :-)

Ja, das hattest du ja bereits beschrieben. Ich kann das mit dem zusammenklappen aber nicht nachvollziehen. Bezüglich der Gelesen-Markierung: das war in der Tat nicht so implementiert, ist aber mit https://github.com/ckruse/cforum_ex/commit/cf8d43ec49e8eada7b481650b9ea34116493236b geändert worden. Es sollte inzwischen also so sein, dass mit Grund gelöschte Postings als gelesen erscheinen.

**Comment by auge8472** [comment]
> Ich kann das mit dem zusammenklappen aber nicht nachvollziehen.

Vielleicht ein Unterschied zwischen Admin und Mod? Vielleicht ein Unterschied zwischen ernanntem und aufgrund Punktestand gewordenem Mod? Vielleicht auch eine Beobachtung, die sich mit der von dir genannten Änderung erledigt hat? Ich weiß es nicht. 🤷‍♂️

Das passiert ja auch nicht alle Tage.

**Comment by ckruse** [comment]
Die Änderung hat nur Auswirkungen auf die Darstellung als gelesen, nicht auf das zusammenklappen. Einen Unterschied in den Rechten kann das auch nicht ausmachen.

Kannst du das bitte bei Gelegenheit nochmal genauer beobachten und dann berichten? Ich vermute eher ein Missverständnis oder so.

**Comment by auge8472** [comment]
Mache ich.

**Comment by auge8472** [comment]
Zur Info: gerade hatte ich einen [Spam-Eintrag von heute früh (2021-04-27 00:04)](https://forum.selfhtml.org/self/2021/apr/22/gelost-http-downloads-und-datei-berechtigungen/1787803#m1787803) gefunden und aufgerufen (in der Nicht-Admin-Ansicht). Im Gegensatz zu meinen früheren Beobachtungen wird der Sapm-Eintrag als gelesen klassifiziert und somit auch der Thread in der Übersicht zusammengeklappt. Das entspricht meinen Erwartungen, womit sich dieses Ticket wohl erledigt haben dürfte.
