### ISSUE TITLE
Schalter srt (zeige gelesene Threads) bleibt nicht erhalten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#24]
Ich wähle "gelesene Threads anzeigen", lese einen Thread und klicke auf "alle Foren". Dann sind alle Threads wieder zu.

Es wäre schön, wenn die Einstellung so lange erhalten bleibt, bis man sie wieder ausschaltet.

Als angemeldeter Benutzer gibt es eine entsprechende Einstellung.

**Comment by ckruse** [comment]
Ja, das gleiche gilt für `view_all=yes`… dafür muss ich persistente URL-Flags einführen und eine eigene Link-Funktion.

Was ich damit sagen will: ist geplant.

**Comment by Rolf-B** [comment]
Bei view_all=yes ist das besonders lästig. Ist man in der Admin-Ansicht und möchte einen gelöschten Beitrag aufrufen, geht das view_all ebenfalls verloren und man muss es von Hand in die URL hineinpfriemeln.

**Comment by ckruse** [comment]
Puh, endlich - das war ein hartes Stück Arbeit. Implementiert mit <https://github.com/ckruse/cforum_ex/compare/c074835a..f66a436c>

**Comment by MatthiasApsel** [comment]
Auf den ersten Blick sieht es so aus wie: Ersetze routes durch path. :-p

**Comment by ckruse** [comment]
Wenns nur so einfach gewesen wäre... 🤷‍♂️
