### ISSUE TITLE
Suche im Forum: Quoted Strings

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#242]
Ich frag mich ja, ob wir hier in Form der Issues korrekt unterwegs sind. Das wird ja langsam zu einem "Forum über's Forum" ;)

Jedenfalls: Ich suche einen Thread von mir, wo ich Matthias ein "mach ich" versprochen hatte. Suche ich aber nach "mach ich", finde ich jede Menge Threads, wo "mach", "machst" oder "mache" alleine steht.  Mein gesuchter Beitrag ist deutlich weiter unten. Wenn ich denn nach Datum sortiere. Nach Relevanz sortiert bin ich nicht mal auf Seite 1 dabei. 

Eine Autorensuche hat irgendwie auch nicht auf Anhieb geklappt. author:"Rolf B" führte bei ersten Abfragen zu nichts. Später dann doch. Keine Ahnung was ich da falsch gemacht habe. Eine Suche nach Autoren mit Leerzeichen im Namen scheint fummelig zu sein.

Bei Sortierung nach Relevanz würde ich erwarten, dass Beiträge mit der Wortfolge "mach ich" ganz oben stehen. Weit gefehlt. Werden quoted strings überhaupt als zusammenhängende Einheit gesucht? Erwarten würde ich das.

**Comment by ckruse** [comment]
Bezüglich der Issues: genau so sind wir richtig „unterwegs.“ Dass das Forum sich immer wieder um sich selbst dreht ist nicht erstrebenswert…

Die Suche nutzt im wesentlichen die Volltextsuche von PostgreSQL. Gequotete Strings werden dabei als ein Suchbegriff gewertet, siehe https://github.com/ckruse/cforum_ex/blob/master/lib/cforum/search/query.ex#L60 - was dann PostgreSQLs fulltext search daraus macht, ist wieder was anderes.

Genauer kann ich mir das erst heute Abend anschauen. Bin arbeitstechnisch voll ausgebucht.

**Comment by ckruse** [comment]
Also, der Grund warum `"mach ich"` nicht alles mit "mach ich" drin findet ist, dass `to_tsquery('german', '''mach ich''')` das `ich` als stop word erkennt und damit aus der Suche streicht:

~~~sql
select to_tsquery('german', '''mach ich''');
~~~

gibt

~~~
 to_tsquery
------------
 'mach'
(1 row)
~~~

**Comment by Rolf-B** [comment]
Das ist nicht alles. Nach kurzem Basteln zwei Nichtstopworte gefunden: "heute" und "oben". Suchprinzip: Suche nach dem Wort allein. "ich" liefert 0 Treffer. Andere Worte wie "nicht" oder "nichts" ebenfalls. Aber bei Einzelsuche nach "heute" und "oben" kamen jeweils Treffer.

Kombisuche nach "heute oben" liefert 61 Treffer. Jede Menge Kram mit "heute" und "oben" drin, aber der Beitrag von TS von Weihnachten 2019, wo er von "heute oben im Harz" spricht, ist nicht auf der ersten Seite. Es ist übrigens total Wurst, ob ich mit oder ohne Anführungszeichen suche, es bleiben 61 Treffer. Und damit wird die Wurst zum Käse - Anführungszeichen werden nicht beachtet.

**Comment by ckruse** [comment]
Doch, die werden beachtet. Sie wirken sich allerdings nicht so aus, wie du das erwartest. `'heute oben'` ergibt als Konstrukt das hier: `WHERE foo @@ to_tsquery('german', '''heute oben''')`. `'''heute oben'''` ergibt diese TS query:

~~~
select to_tsquery('german', '''heute oben''');
   to_tsquery
-----------------
 'heut' & 'oben'
~~~

`heute` und `oben` als einzelne Suchterms ergibt `WHERE foo @@ to_tsquery('german', 'heute') AND foo @@ to_tsquery('german', 'heute')`.

**Comment by ckruse** [comment]
Ich habe hier mal eine `LIKE`-query „nachgelagert“, so dass bei Phrasen der exakte Treffer gefunden werden muss.

**Comment by Rolf-B** [comment]
Also ich habe jetzt erstmal Paradox Doku gelesen. to_tsquery "normalisiert worte und erzeugt eine tsquery" - ok. Aber dann sollte doch ein Lexem mit Space darin auch **ein** Lexem bleiben, und nicht zwei draus werden. Das ist aber in deinem Beispiel passiert. Es scheint, als ob diese Quoting nur im tsvector funktioniert; es ist auffällig, dass in <https://www.postgresql.org/docs/13/datatype-textsearch.html> nur bei tsvector von quoted lexemes die Rede ist.
