### ISSUE TITLE
Benutzereinstellung Links in neuem Tab öffnen gibt es nicht mehr

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#25]
Ist das geplant?

**Comment by ckruse** [comment]
Ja, das ist Absicht.

**Comment by MatthiasApsel** [comment]
Wie? Es ist Absicht, dass wieder einzubauen? Es ist Absicht, dass es so ist?

**Comment by ckruse** [comment]
es ist Absicht, dass das Feature „Links in neuem Fenster öffnen” nicht mehr existiert :)

**Comment by MatthiasApsel** [comment]
Hm. Schon wieder vanilla.

**Comment by ckruse** [comment]
Vanilla?

**Comment by MatthiasApsel** [comment]
Naja, dann muss ich es eben nachbauen.

**Comment by ckruse** [comment]
Ach so.

naja, das Feature gehört zu den Dingen, die außer zwei Accounts keiner benutzt hat und mir sehr viel Arbeit bereitet hätte… sorry

**Comment by MatthiasApsel** [comment]
Ok. Aber warum ist das viel Arbeit?

~~~php
<?php if($option):?> target="_blank"<?php endif;?>
~~~

geht das in Elixir nicht auch so einfach?

**Comment by ckruse** [comment]
Wenn ich das so mache, muss ich das an jeder Stelle, an der ein Link generiert wird tun. Und jedesmal, wenn eine Erweiterung oder Änderung ansteht, muss ich das auch an allen Stellen von Hand ergänzen. Keine gute Lösung...

Die richtige[tm] Lösung wäre es, das in einer Funktion zu kapseln, die Links generiert und die dann überall zu verwenden. Wie bei dem srt-Flag.

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Naja, eigentlich nur bei .problematic-site und .cf-posting-content.
