### ISSUE TITLE
in der Vorschau wird die Verabschiedung als h3 gerendert

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#27]

**Comment by ckruse** [comment]
Beispiel notwendig…

**Comment by MatthiasApsel** [comment]
![grafik](https://user-images.githubusercontent.com/2847625/59962782-31c89d80-94ea-11e9-8402-a9c35fdcff2a.png)

Oder wie soll das Beispiel aussehen?

Im endgültigen Beitrag ist es dann wieder richtig.

**Comment by ckruse** [comment]
Ich benötige das Markdown, dass dazu führt ;-)

**Comment by MatthiasApsel** [comment]
~~~
Hallo alle,



Bis demnächst  
Matthias
-- 
Pantoffeltierchen haben keine Hobbys.  
¯\\\_(ツ)\_/¯
~~~

**Comment by MatthiasApsel** [comment]
Hallo alle,



Bis demnächst  
Matthias
-- 
Pantoffeltierchen haben keine Hobbys.  
¯\\\_(ツ)\_/¯

Da es hier auch so ist, ist es wohl mein Fehler.

Hallo alle,



Bis demnächst  
Matthias

-- 
Pantoffeltierchen haben keine Hobbys.  
¯\\\_(ツ)\_/¯

Mal einen Zeilenumbruch probieren.

**Comment by MatthiasApsel** [comment]
Dann ist aber eine Leerzeil zwischen Verabschiedung und Sigantur. Das sieht auch nicht schön aus.
