### ISSUE TITLE
@@user sollte nicht zu einer Mention führen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#29]

**Comment by ckruse** [comment]
Warum nicht?

**Comment by MatthiasApsel** [comment]
Weil es in V4 auch nicht so war ;-)

**Comment by ckruse** [comment]
Das halte ich für einen schlechten Grund ;P

**Comment by MatthiasApsel** [comment]
Ja, ich auch. Zweiter Grund: Es sieht doof aus.

![grafik](https://user-images.githubusercontent.com/2847625/59966366-3148fa80-951c-11e9-8d29-afb31794df64.png)
