### ISSUE TITLE
Gelöschter, aber ungelesener Beitrag führt dazu, dass ein Thread für einen Nichtmoderator ungelesen bleibt?!

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#301]
Das ist meine Hypothese für dieses Problem von Ottogal:

<https://forum.selfhtml.org/self/2021/apr/28/imagesslider-mit-einem-sprunganker-verlinken/1788104#m1788104>

Gibt es das Testforum noch, wo man mir (vorübergehend) Adminrechte geben könnte, so dass ich das mit Testusern mal nachstellen könnte? Ich möchte das ungern im Hauptforum tun, und die Admins (wer ist das eigentlich noch außer Matthias S?) eigentlich auch nicht behelligen.

**Comment by ckruse** [comment]
Nein, gibt es nicht.

Es bliebe erstmal zu klären, wass Ottogal damit meint. Was ist seine Erwartungshaltung und was passiert? Denn natürlich lässt sich auch ein Thread mit gelöschten Nachrichten als gelesen markieren.

**Comment by Rolf-B** [comment]
Ich korrigiere: Er **soll** sich markieren lassen - und nach dem, was er schreibt, tut Otto das auch. 

Was er tut und was er erwartet, ist doch klar dargestellt, finde ich. Er setzt den Thread auf gelesen, und er hat das auch bei jedem einzelnen Beitrag versucht (was ich mir mühsam vorstelle, man muss da vermutlich bei jedem Posting auf "mach ungelesen" - "mach gelesen" klicken), und der Thread wird ihm nach wie vor angezeigt. Was nicht sein sollte.

Meine Hypothese ist, dass für einen Nicht-Moderator ein ungelesener, gelöschter Beitrag beim Setzen von "Thread ist Gelesen" übergangen wird, bei der Abfrage auf "Ist der Thread sichtbar" aber nicht. Für Dich und mich, mit Admin- oder Moderatorenrechten, fällt das nicht auf.

**Comment by ckruse** [comment]
Vielleicht weniger Hypothesen formulieren ;-)

Es ist kein Stück dargelegt, was Ottogal damit meint. Er schreibt, dass er diesen Thread nicht als gelesen markieren kann, weder „weder individuell noch beim markieren aller Beiträge als gelesen.“ Wahrscheinlich meint er mit „individuell“ den „markiere Thread als gelesen“-Button neben jedem Threadbaum und mit „beim markieren aller Beiträge als gelesen“ den entsprechenden Button oben in der Button-Leiste. Aber hier nehme ich auch nur an.

Was er mit „lässt sich nicht als gelesen markieren“ meint ist absolut unklar, du nimmst da eine Menge Dinge an aus einem Halbsatz, den Ottogal verfasst. Was er allerdings tatsächlich damit meint weiss ich nicht.

Deine Hypothese ist so wie formuliert auf jedenfall nicht zutreffend.

**Comment by ckruse** [comment]
So, ich hab jetzt mal in die Datenbank geschaut.

Unter der Voraussetzung, dass du recht hast und er meint **eigentlich**, dass der Thread sich nicht schliesst obwohl alle Beiträge als gelesen markiert sind: das liegt daran, dass er den Thread manuell als geöffnet markiert hat, über das Ordner-Symbol neben dem Thread. Wenn er dort nochmal draufklickt, wird der Thread auch wieder automatisch geöffnet bzw geschlossen.

**Comment by Rolf-B** [comment]
Ich bin vielleicht zu blöd. Aber was hat das Ordnersymbol mit dem Verhalten bei Gelesen zu tun? Wieso sollte sich ein Thread in der Übersicht zuklappen, nur weil ich alles gelesen habe? Sowas kenne ich überhaupt nicht.

**Comment by ckruse** [comment]
Weil das eine häufig genutzte Konfigurationsoption ist:

<img width="328" alt="Bildschirmfoto 2021-05-06 um 11 49 23" src="https://user-images.githubusercontent.com/175095/117278519-21610800-ae61-11eb-9339-e492fda335fa.png">

Wenn Ottogal die aktiviert hat und er erwartet, dass der Thread zusammengeklappt wird (beides Annahmen, die sich aus dem Satz nicht herleiten lassen!), dann ist diese Erwartungshaltung falsch, denn er hat den Thread manuell aufgeklappt (via Ordner-Symbol), und das überschreibt die Automatik.

**Comment by Rolf-B** [comment]
Ich begreife Dich nicht. Du vergleichst Äpfel und Apfelbäume - also Beiträge und Threads.  Beide haben eine Funktion zum auf- und zuklappen, und das sind verschiedene Dinge. 

Threads: Das Ordner-Symbol in der Threadübersicht, das offenbar drei Zustände hat: unberührt, zu, auf. Das war mir neu.
Beiträge: Ein Button "einklappen" / "aufklappen" am Beitrag. Hat der auch drei Zustände?

Die von Dir genannte Einstellung nennt Beiträge, nicht Threads. Meint sie Threads? Wie auch immer - sie ist bei mir in beiden Deutungen wirkungslos. 

- Wenn sie sich auf **Beiträge** bezieht, sollten die gelesenen Postings in einer nested Threadansicht beim Öffnen Auf- oder Zugeklappt sein, je nach Einstellung. Das ist nicht so, bei mir ist das eröffnungsposting immer aufgeklappt und die gelesenen Antworten immer zugeklappt. Ungelesene sind offen. Und wenn ich den Thread öffne (durch Klick auf den Eröffnungsbeitrag), werden alle Antworten als Gelesen markiert, obwohl "markiere Beiträge in der Nested-Ansicht als gelesen, wenn sie in den sichtbaren Bereich scrollen" bei mir aus ist. Also auch wirkungslos.

- Wenn sie sich auf **Threads** bezieht und an ist, sollten gelesene Threads in der Threadübersicht automatisch zugeklappt sein. Das ist nicht der Fall, sie sich immer aufgeklappt. Das ist mir allerdings nie aufgefallen, weil ich (a) die Einstellung so nicht gedeutet habe und (b) bei mir eingestellt ist, dass gelesene Threads ausgeblendet werden.

Ich habe Ottogal nun meine Deutung mal gespiegelt und ihn um Stellungnahme gebeten.

**Comment by ckruse** [comment]
Sorry, falscher Screenshot. Der hier ist gemeint.

<img width="529" alt="Bildschirmfoto 2021-05-06 um 12 23 30" src="https://user-images.githubusercontent.com/175095/117283258-e6ad9e80-ae65-11eb-80cc-66f27c810244.png">

Bezüglich der „drei Zustände“ des Ordner-Buttons: nein, es gibt zwei Zustände. Verändert oder default. Verändert ist immer das Gegenteil von Default. Z.B. bei „Zeige Threads per Default geöffnet“ sind die möglichen Zustände für einen Thread: „geschlossen“ und Default.

**Comment by Rolf-B** [comment]
Ja ok. Aber, wie geschrieben, ist auch dieser Schalter bei mir wirkungslos. Interagiert der mit noch etwas anderem?

**Comment by ckruse** [comment]
Ich weiss nicht, was du mit „wirkungslos“ meinst. Du lässt immer so viel Kontext weg! Das Forum ist durch die umfangreichen Konfigurationsoptionen ein sehr komplexes System, deshalb benötige ich bei Meldungen **immer** die Angaben beobachtetes Verhalten, erwartetes Verhalten und Nutzeraccount. Mit letzterer Angabe kann ich die Konfiguration nachsehen.

**Comment by ckruse** [comment]
Was auch immer du meinst: dieses Verhalten solltest du beobachten:

- Threads per Default geöffnet
- Threads zusammenklappen wenn gelesen
- Admin-Ansicht ist inaktiv
- keine Anpassung des Geöffnet/Geschlossen-Status durch Klick auf das Ordner-Symbol

Wenn alle drei Bedingungen erfüllt sind sollten Threads in der Thread-Liste, wenn alle zum Thread gehörenden Beiträge gelesen wurden,  automatisch zusammengeklappt werden.

**Comment by Rolf-B** [comment]
Meinen Nutzeraccount Rolf B kennst Du doch. Oder brauchst Du die Nummer - 6547 ?

Zum Kontextmangel: Die Schalter "Threads per Default geöffnet" und "Klappe Threads zusammen, wenn sie vollständig gelesen wurden" habe ich jetzt erst entdeckt. Die sind bei Personalisierung, nicht bei Lesbarkeit, deswegen hatte ich sie total übersehen. Die Darstellungsvarianten des Forums sind komplex, man könnte fast schon sagen: zu komplex, und diese beiden Schalter finde ich fehlplatziert. 

Ich habe Ottogal nun auch auf diese beiden Schalter hingewiesen und - hoffentlich - klarer nachgefragt welches vermeintliche Fehlverhalten er meint.

**Comment by ckruse** [comment]
Der Kommentar, welche Infos ich benötige, war eher allgemein als auf diesen spezifischen Fall gemünzt, damit klar ist, warum du mich so verwirrt hast ;-)

Bezüglich der Komplexität: ja, das sehe ich auch so. Deshalb habe ich von V4 auf V5 bereits viele Optionen ersatzlos gestrichen. An mehr habe ich mich allerdings nicht rangetraut, du kennst ja das Genöle, wenn etwas nicht mehr da ist…

**Comment by Rolf-B** [comment]
Was ich auch verwirrend finde, ist das Verhalten des Ordner Buttons. Er hat nach deiner Erklärung zwei Zustände: "zeige Default" und "zeige Gegenteil vom Default". Und das Forum hat zwei Default-Zustände für Threads: eingeklappt oder ausgeklappt. Damit gibt es vier Situationen:
Forum eingeklappt, Button default: eingeklappt
Forum eingeklappt, Button opposite: ausgeklappt
Forum ausgeklappt, Button default: ausgeklappt
Forum ausgeklappt, Button opposite: eingeklappt

Das hat Konsequenzen, über die ich noch nie nachgedacht habe. Aber vielleicht verstehe ich Dich auch nach wie vor miss. Es ist mit einem User auch nicht so einfach, herumzuprobieren, und ich möchte auch nicht blindlings anonym Müll posten.

* Wenn ein Thread eingeklappt ist, weiß ich nicht, ob er eingeklappt ist weil das Forum ihn einklappen will, oder weil ich den Button geklickt habe. Der Button zeigt mir nicht, ob er im "default" oder "gegenteil" Modus ist.
* Wenn ein Thread gelesen ist und ich ihn aufklappen will, muss ich den Button auf "Gegenteil" stellen. Nun kommt ein Posting hinzu. Das Forum möchte den Thread nun zeigen, der Button steht auf "Gegenteil", und damit wird der Thread versteckt. Oder setzt Du alle User-Einstellungen dieses Buttons für diesen Thread auf Default zurück, wenn ein neuer Beitrag hinzukommt?

**Comment by ckruse** [comment]
> Forum eingeklappt, Button default: eingeklappt
> Forum eingeklappt, Button opposite: ausgeklappt
> Forum ausgeklappt, Button default: ausgeklappt
> Forum ausgeklappt, Button opposite: eingeklappt

Der Button hat nicht den Zustand „opposite“ sondern „open“ oder „closed,“ abhängig davon, was man als Default ausgewählt hat. „Forum eingeklappt“ oder „Forum ausgeklappt“ gibt es in dem Sinne nicht. Es gibt diese Zustände:

- Button "open": ausgeklappt
- Button "closed": ausgeklappt
- Button NULL: Default

Default kann diese Werte haben:

- "open"
- "closed"

Wenn ein Thread durch das Default geöffnet dargestellt wird, dann kann dieses Default für Threads überschrieben werden, die vollständig gelesen markiert sind.

Die Unterscheidung ist wichtig, denn wenn ein User den Default-Status umstellt ist trotzdem der Button-State wie vorher eingestellt! Also z.B. der User hat Threads per default offen und schliesst einen Thread X über den Button, stellt dann das Default auf geschlossen, dann ist der Button-State für Thread X weiterhin geschlossen. Ein Klick setzt den State auf geöffnet. Und ein weiterer Klick setzt den State auf NULL.

> Wenn ein Thread eingeklappt ist, weiß ich nicht, ob er eingeklappt ist weil das Forum ihn einklappen will, oder weil ich den Button geklickt habe. Der Button zeigt mir nicht, ob er im "default" oder "gegenteil" Modus ist.

Richtig.

> Wenn ein Thread gelesen ist und ich ihn aufklappen will, muss ich den Button auf "Gegenteil" stellen. Nun kommt ein Posting hinzu. Das Forum möchte den Thread nun zeigen, der Button steht auf "Gegenteil", und damit wird der Thread versteckt.

Hä? Das ist natürlich nicht der Fall. Wie ich bereits oben schrieb: das betätigen des Buttons überschreibt die Automatik. Wenn du den Button angeklickt hast, dann wird der Thread nicht mehr automatisch geöffnet oder geschlossen.

**Comment by ckruse** [comment]
Tjo, [da hatte ich wohl recht](https://forum.selfhtml.org/self/2021/apr/28/imagesslider-mit-einem-sprunganker-verlinken/1788162#m1788162). Ottogal erwartet, dass der Thread eingeklappt wird. Wird er aber nicht, weil er ihn von Hand ausgeklappt hat.

**Comment by Rolf-B** [comment]
> Hä? Das ist natürlich nicht der Fall. 

Also hatte ich doch recht mit meinen drei Zuständen. Open / Close / NULL (Default). Dem hattest Du widersprochen. Und ich verstehe es richtig, dass der "Default" Zustand nicht wieder herstellbar ist?

**Comment by ckruse** [comment]
> Also hatte ich doch recht mit meinen drei Zuständen. Open / Close / NULL (Default).

Nur halb. Wenn du „Threads per default offen“ ausgewählt hast, kannst du den Button-State „open“ nicht erreichen. Er ist immer „Closed“ oder NULL. Du müsstest den Default-State auf geschlossen setzen, den Button betätigen und dann den Default-State auf offen setzen, um einen Button-State „open“ bei Default-Wert „open“ zu erreichen.

> Und ich verstehe es richtig, dass der "Default" Zustand nicht wieder herstellbar ist?

Nein, das verstehst du falsch. Sofern du das Default nicht änderst ist der Button-State immer das Gegenteil vom Default oder NULL.

**Comment by Rolf-B** [comment]
Ok, ich habe jetzt etwas gespielt. Welchen Nutzen hat die Einstellung "Threads per Default schließen"? Weil - wenn eine neue Antwort eintrifft, sehe ich sie nicht. Zumindest entdecke ich keinen "Hier wurde neu geantwortet" Marker. Die Kombi "Threads per Default öffnen" plus "Gelesene Threads zusammenklappen" ist sinnvoll. Da klappen neue Antworten den Thread auf. 

Aber bei "per Default schließen" sehe ich die neue Antwort nicht. Ich habe den Thread nicht abonniert, und bekomme deshalb auch keine Benachrichtigung. Ich müsste noch "vollst. gelesene Threads verstecken" hinzufügen, um zumindest zu bemerken, dass sich was getan hat. Ist es deine Erwartung, dass ich im "Per Default schließen" Modus jeden Thread abonniere, bei dem ich sehen will, ob Antworten eintreffen?

Ich bin vielleicht zu lange mit PHPBB unterwegs gewesen und zu sehr auf eine bestimmte Nutzungsweise festgefahren, um mir eine solche Benutzungsart vorzustellen.

**Comment by ckruse** [comment]
> Welchen Nutzen hat die Einstellung "Threads per Default schließen"?

Ich nutze diese Einstellung nicht, und würde es auch nie tun. Aber das Geschrei war groß, als ich sie abschaffen wolltet – sie wird also offensichtlich genutzt. Genau so das deaktivieren des Pagings. Das ergibt in meiner Welt wenig Sinn, aber man muss sich halt damit abfinden, dass User andere Nutzungsmuster haben als ich.

> Ist es deine Erwartung, dass ich im "Per Default schließen" Modus jeden Thread abonniere, bei dem ich sehen will, ob Antworten eintreffen?

Es geht nicht um *meine* Erwartung, es geht die Erwartung des Users. Keine Ahnung, wie diese Leute das Forum nutzen – ich praktiziere kein Usertracking und kann es dir deshalb auch nicht sagen. Ich weiss aber, dass rund 10 % der User dieses Feature nutzen.

**Comment by Rolf-B** [comment]
Ok, nach dem, was Otto antwortet, ist meine Hypothese final widerlegt.
