### ISSUE TITLE
"alle einklappen" liegt über dem Text

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#31]
Wie der "alle einklappen"-Button in den meisten Threads im Weißraum neben den Postings mitläuft, gefällt mir. Leider führt das bei langen Threads dazu, dass die Postings in den untersten Ebenen genau unterhalb dieses Buttons zum liegen kommen, der Text wird überdeckt und der mitlaufende Button irritiert beim lesen.

Schön wärs, wenn der Button in diesen Fällen links laufen würde - da wäre genug Platz. Ob und wie das machbar ist kann ich nicht beurteilen, aber in der aktuellen Variante irritierts.

[Beispiel hier](https://forum.selfhtml.org/self/2019/may/20/heise-punkt-de-google-sperrt-android-updates-und-den-play-store-fuer-huawei/1749191#m1749191). Screenshot:
![Unbenannt](https://user-images.githubusercontent.com/11651007/59965871-09559900-9514-11e9-804f-99822bdee1a8.PNG)

**Comment by ckruse** [comment]
Ich weiß, das ist ungünstig. Ich weiss nur keine bessere Lösung. Zumal der Button dort auf Wunsch von @MatthiasApsel ist…

**Comment by MatthiasApsel** [comment]
Siehe issue #32

**Comment by auge8472** [comment]
Wäre es eine Option, den Button mit `transform: rotate();` umzukippen und an den rechten Viewportrand zu verfrachten? Ja, er wäre bei kurzen Threads, die nicht annähernd an den rechten Viewportrand heranreichen, weit weg. Er wäre aber immer dort (wiederauffindbar) und bei Situationen, wie der im Screenshot gezeigten, aus dem Weg.

**Comment by ckruse** [comment]
ja, das wäre glaube ich eine gute Variante, auch wenn ich den linken Bildschirmrand wählen würde.

**Comment by MatthiasApsel** [comment]
https://github.com/ckruse/cforum_ex/issues/32#issuecomment-504692871

**Comment by ckruse** [comment]
Oh. Habe ich tatsächlich nicht gesehen, ist untergegangen. Sorry.
