### ISSUE TITLE
Vorschlag für "alle ausklappen" bzw. "alle einklappen"

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#32]
![grafik](https://user-images.githubusercontent.com/2847625/59966246-c7c7ec80-9519-11e9-837f-2c82ff7f9d30.png)

Wäre das eine Option?

**Comment by ckruse** [comment]
gefällt mir überhaupt nicht, viel zu missverständlich… sorry

**Comment by MatthiasApsel** [comment]
Aber die Lernkurve dürfte so groß nicht sein.

**Comment by MatthiasApsel** [comment]
![grafik](https://user-images.githubusercontent.com/2847625/59968181-b42a7f00-9535-11e9-9010-d1aa2bd243f2.png)

Leider will das JS nicht arbeiten:

~~~js
if (document.getElementById("folding-all-button")) {
  document.getElementById("folding-all-button").innerText = "⇣";
}
~~~

innerhalb eines DOMContentLoad-handlers.

**Comment by ckruse** [comment]
Du kannst das jetzt über folgendes JS erreichen:

~~~ js
document.addEventListener("cf:foldingAllButtonChanged", function(ev) {
  ev.detail.innerText = "⇣";
})
~~~
