### ISSUE TITLE
Falsch aufbereitete Fußnote "zerstört" das Forum

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#324]
Hallo Christian,

dieser Text[^1] enthält eine Doppelfußnote[^2].

[^1]:[^2]: Kuck mal wer da füßelt!

Niemand sagt, dass das korrektes Mark- oder Kramdown ist, und hier im Github wird das lediglich ignoriert.

Im CForum zündet es eine Bombe: Es ersetzt es die textarea zum Bearbeiten des Beitrags durch "uups, es ist etwas schiefgegangen", d.h. man kann nur noch verwerfen. Oder so, wie ich, in die DevTools gehen und den Entwurf im LocalStorage am offenen Herzen operieren.

Immerhin kann man nicht speichern - wer weiß, was passiert, wenn so ein Thread im Forum für alle sichtbar würde. 

Sobald die Zeichenfolge [^1]:[^2]: eingegeben ist, verschwindet der Edit-Bereich (Textarea und Vorschau) und in der Konsole erscheint

~~~
react-dom.production.min.js:209 TypeError: Cannot read property 'type' of undefined
    at Array.<anonymous> (index.js:338)
    at u.process (parser_core.js:51)
    at b.parse (index.js:524)
    at b.render (index.js:544)
    at W (live_preview.js:24)
    at Yi (react-dom.production.min.js:153)
    at La (react-dom.production.min.js:175)
    at wo (react-dom.production.min.js:263)
    at pu (react-dom.production.min.js:246)
    at fu (react-dom.production.min.js:246)
~~~

sowie

~~~
fetch.js:11 Refused to connect to
 'https://appsignal-endpoint.net/collect?api_key=7f5fcb04-c262-4b2e-b383-9ce2a7b4a821&version=1.3.12'
because it violates the following Content Security Policy directive: "connect-src 'self' wss://forum.selfhtml.org".
~~~

**Comment by ckruse** [comment]
Upstream bug: https://github.com/markdown-it/markdown-it-footnote/issues/42
