### ISSUE TITLE
Antwort-akzeptieren-Button bei fremden Threads 

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#35]
Mir als Punkte-basiertem Moderator wird der Antwort-akzeptieren-Button in jedem Posting jedes Threads angezeigt. Beim klicken des Buttons erscheint für ein paar Zehntelsekunden ein kleiner Kringel, es kommt aber keine Vollzugs- oder Fehlermeldung und im Eröffnungsposting wird das soeben markierte Posting *nicht* als akzeptierte Antwort gelistet. Es scheint sich also um ein kosmetisches Problem, dass der Button nicht nur dem Threadersteller angezeigt wird, zu handeln.

**Comment by ckruse** [comment]
Dass der Button angezeigt wird, ist richtig, wenn du Moderator bist. Moderatoren können Antworten akzeptieren und die Akzeptiert-Markierung entfernen.

Dass der Button kaputt ist, ist nicht richtig :-)

**Comment by auge8472** [comment]
> Moderatoren können Antworten akzeptieren und die Akzeptiert-Markierung entfernen.

Das ist neu, oder? Bisher (cforum 4) ist mir diese Funktion nicht aufgefallen.

> Dass der Button kaputt ist, ist nicht richtig :-)

Oder so

**Comment by ckruse** [comment]
Ich müsste es nachschauen, aber AFAIR konnten das auch damals[tm] schon Moderatoren.

**Comment by ckruse** [comment]
Kann es sein, dass du nur nicht gesehen hast, dass die Nachricht akzeptiert wurde? Klick mal „daneben,“ wenn du eine Nachricht akzeptiert hast oder lade neu.

Das Problem ist, dass durch den Focus auf den Button man das ggfls einfach nicht sieht… man sollte vermutlich über deine andere `:focus`-Markierung nachdenken.

**Comment by auge8472** [comment]
> Kann es sein, dass du nur nicht gesehen hast, dass die Nachricht akzeptiert wurde? Klick mal „daneben,“ wenn du eine Nachricht akzeptiert hast oder lade neu.

Also: Wenn ich den Akzeptieren-Button klicke, wird der grün (ein im übrigen für mich wenig von dem Orange (oder Gelb?) des gehoverten Buttons unterscheidbares Grün). Das war gestern auch schon so. Eine Meldungsbox, die es bisher zum Beispiel bei Fehlern oder erfolgreichen Bewertungen gab, wird nicht angezeigt. Allerdings wird mir im Eröffnungsposting die akzeptierte Antwort auch als solche aufgelistet. Das war *meiner Erinnerung nach* gestern *nicht so*.

**Comment by ckruse** [comment]
Ich habe da nichts geändert… ;-)

Aber ich denke, es sollte wieder einen Alert geben, ja, um nicht so verwirrend zu sein.
