### ISSUE TITLE
Sichtbare Beschriftung Teil des zugänglichen Namens

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum_ex#36]
[Sichtbare Beschriftung Teil des zugänglichen Namens](https://testen.bitv-test.de/index.php?a=di&iid=117&s=n)

Mein Gegenvorschlag: Erst Avatar (nicht verlinkt), dann Name des Beitrages und Uhrzeit, in Klammer dahinter den Namen des Autors als Link zum Profil:

😜 [**Classic Forum V5 - noch kleine Bugs** 22.06.2019 20:19](#) ([_Der Martin_](#))

Übertragen aus https://github.com/ckruse/cforum/issues/802

**Comment by MatthiasApsel** [comment]
Im Threadbaum und in der Forumsübersicht kann ich mir das sehr gut vorstellen. In der Posting-Ansicht eher nicht. Aber auch braucht der Avatar nicht verlinkt zu sein.
