### ISSUE TITLE
Suche in Zitaten nach Autor zeigt nur den Autornamen, aber nicht das Zitat

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#370]
Ich habe angesichts des neuesten "funktioniert nicht" Postings im Forum nach passenden Weisheiten in der Zitatesammlung gesucht und "author:cheatah"  eingegeben.

In der Trefferliste steht pro Zitat "Cheatah". Aber nicht der Zitatinhalt. Suche ich nach "funktioniert", finde ich Autornamen plus Zitatinhalt.

Husseldiguggeldu, denke ich (Siehe Zitat 186 ;) )

**Comment by ckruse** [comment]
Ich zeige den Inhalt jetzt immer. Ihn auszublenden wenn der Suchstring nicht darin gefunden wurde ist irgendwie eine doofe Idee gewesen.
