### ISSUE TITLE
Vollständig gelesene Threads klappen nicht zu

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#38]
Ich lesen die Postings eines Threads in der Einzelansicht in einem Tab je Thread, wobei die Übersichtsseite des/eines Forums in einem anderen Tab offen bleibt. Trotzdem ich alle Postings aufgerufen hatte, wird der Thread in der Übersichtseite nicht live zugeklappt. Mit der 4-er Forensoftware hat das noch funktioniert.

Soweit ich mit dem Inspektor der Entwicklerwerkzeuge des Firefox ermitteln kann, wird die Klasse `visited` im `header`des Postings im Threadbaum auf der Übersichtsseite (momentan "alle Foren") nicht instantan gesetzt. Die Postings werden aber als aufgerufen *angezeigt* (wegen `:visited`). Erst nach den Neuladen der Übersichtsseite (bei mir per User-JS alle 20 Minuten) ist der Thread zugeklappt.

**Comment by ckruse** [comment]
Ja. Das gleiche gilt für so Sachen wie Bewertungen udgl. Ist geplant aber noch nicht umgesetzt. V5 hat noch nicht an allen Stellen feature parity zu V4.

**Comment by auge8472** [comment]
Ist es in deinem Interesse, dass ich (oder wer auch immer) weiter melde, was mir auffällt (quasi als Tasklist) oder nervt das, weil das Dinge sind, die dir bekannt sind?

**Comment by ckruse** [comment]
Nein, das melden ist gut! Ich vergesse ja auch Sachen schonmal (man wird älter ;-), da ist eine Liste zum abhaken genau das richtige!

**Comment by ckruse** [comment]
Sollte jetzt umgesetzt sein. Wenn etwas fehlt, bitte nochmal melden, dann hab ich etwas vergessen :)
