### ISSUE TITLE
readme link to phoenix deployment guide broken

### ISSUE THREAD

**Issue by frankxy** [ckruse/cforum_ex#384]
probably - https://hexdocs.pm/phoenix/deployment.html seems right

acktual - http://www.phoenixframework.org/docs/deployment gets 404 

 http://phoenixframework.org/docs/overview auch 404

**Comment by ckruse** [comment]
Tatsächlich sollte der Link einfach weg. Die offizielle Website linkt für Guides auch nur noch auf hexdocs.pm/phoenix
