### ISSUE TITLE
Imageverwaltung - SVGs sprengen den Bildschirm

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#389]
Okay, nicht den Bildschirm, aber das Layout.

Es scheint, als funktioniere ?size=thumb für SVGs nicht. Und weil die SVGs, die auf Seite 2 stehen, eine 2000x2000 Viewbox haben, werden sie 2000px mal 2000px dargestellt und die Darstellung wird eeeetwas unübersichtlich.

Man müsste vermutlich
- ~~der Bilder-Table eine ID geben (id="thumblist" oder so)~~
   *Edit:* Der Body hat die ID images-index, das tut's :)
- im CSS für #images-index td:first-child img ein max-width:100px zuweisen.

Nur in welche scss Datei das reinmuss? admin.scss? 

Kann das querschießen? Soweit ich das Routing, die Controller, Views und Templates bisher durchschaut habe (ASP.NET MVC bringt da gutes Vorwissen mit!), sollte das image/index.html Template keinen anderen Verwender haben. Von daher würd ich sagen: Nö.

Aber sorry, dass ich ständig was neues habe ;)

**Comment by Rolf-B** [comment]
Ich hätte das ja gleich als Pullrequest abgeliefert. Nachdem mir Dedlfix Git erklärt hat, habe ich mir dein Repo lokal geklont und das SCSS geändert - aber für den Pull Request erzählt er was von Personal Access Tokens. Wenn ich die Hilfe richtig deute, müsstest Du mir eins geben damit ich einen Pull Request eintüten kann? Oder brauche ich für Pull Requests einen Fork im Github?

**Comment by Rolf-B** [comment]
By the way (will kein neues Issue aufmachen): werden Bilder, die ich in der Bilderverwaltung lösche, nicht richtig vom Server gelöscht? Ich hatte einen Fehl-Upload, habe ihn aus dem Bilderverzeichnis gelöscht, aber das Bild kann ich in blog.selfhtml.org immer noch abrufen:

<https://blog.selfhtml.org/images/93c12052-e1b4-11eb-bd75-b42e9947ef30.jpg>

Wird da was repliziert und die Bilderverwaltung bereinigt die Replikation nicht?

**Comment by ckruse** [comment]
Für einen Pull Request musst du einen Fork auf Github erstellen, dort deine Änderungen reinpushen und dann via Github-UI den PR erstellen :-)

Das Bild hast du weiterhin gesehen, weil es mit sehr langen Caching-Headern ausgeliefert wird: es war bei dir im Cache. Ich kann es nicht abrufen.
