### ISSUE TITLE
Bewerten von Blog-Beiträgen

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#396]
Henry wollte für den Blog-Beitrag ein +1 geben und konnte nicht. Er sagte, "Klappt aber leider immer noch nicht, kann den Plus-Button nicht anklicken," - d.h. er sieht den Plus Button, sonst hätte er das nicht gesagt.

JürgenB konnte aber. Er hatte Dich auch in seinem Posting erwähnt, mutmaßlich, um Dir zu signalisieren und einen eigenen Beitritt bei Github zu vermeiden. Und es scheint, als hättest Du es erwartungsgemäß nicht bemerkt.

Gibt es Sonderbedingungen für das Bewerten von Blogbeiträgen? In der Forenkonfiguration ist alles unauffällig und Henry hat genug (>3000) Punkte.

**Comment by ckruse** [comment]
Doch, ich habe das bemerkt. Aber ich hatte gestern keine Zeit und habs dann vergessen. Das ist ja der Grund, warum ich immer so auf ein Issue bestehe. Das ist präsent in meiner Email-Inbox und hier auf Github, das kann ich nicht vergessen.

Bzgl des Issues: hm. Man muss Schreibzugriff auf das Forum haben, um bewerten zu dürfen. Vielleicht mal runtersetzen auf „Lesezugriff.“

**Comment by Rolf-B** [comment]
Versteh ich das richtig, dass du dafür was im Code ändern musst? Den in der Einstellung des Forums sehe ich das nicht.

**Comment by ckruse** [comment]
Ja, dazu musste ich was am Code ändern. Der Commit, mit dem ich das geändert habe, ist doch verlinkt? :-) „ckruse closed this in  909352f yesterday“

**Comment by ckruse** [comment]
Äh, falls die Frage war, ob das schon online ist: ne, ist es noch nicht. Ich hab noch einen anderen Bugfix in der Pipeline…

**Comment by ckruse** [comment]
So. 5.6.64 ist released und enthält den Fix.
