### ISSUE TITLE
Den "alle ausklappen"-Button gibt es auch, wenn nichts auszuklappen ist

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#4]

**Comment by ckruse** [comment]
Dann sollte er aber „alle einklappen“ heißen?

**Comment by MatthiasApsel** [comment]
Wenn es nur einen Beitrag gibt, brauchen wir ihn garnicht. "alle einklappen" heißt er ja dann, wenn alle ausgeklappt sind. Das ist auch richtig so.

**Comment by ckruse** [comment]
Ich halte es nicht für sinnvoll, den Button auszublenden, wenn es nur 
einen Beitrag gibt. Das macht das UI schwieriger zu verstehen und 
inkonsistent. Der Button sollte immer da sein, nur halt die Beschriftung 
sollte sich entsprechend anpassen.

**Comment by MatthiasApsel** [comment]
Das verstehe ich. Also: Wenn alle (n > 0) ausgeklappt sind, heißt er alle einklappen.

**Comment by ckruse** [comment]
So habe ich es mir gedacht, ja. Ist das nicht der Fall? 🤔

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Nein, wenn der einzige Beitrag ausgeklappt ist, steht trotzdem "alle ausklappen" da.
