### ISSUE TITLE
/all/feeds/atom funktioniert nicht

### ISSUE THREAD

**Issue by count-z** [ckruse/cforum_ex#40]
Der Link zu den RSS bzw. Atom Feeds für alle Foren erzeugt nur eine Fehlermeldung. Für einzelne Unterforen klappt es

**Comment by ckruse** [comment]
Hm, wie hast du das getestet? Bei mir funktioniert es.

**Comment by count-z** [comment]
indem ich https://forum.selfhtml.org/all/feeds/atom mit Firefox aufgerufen habe aber ja, jetzt geht es bei mir auch. Vielleicht lief irgendwas noch nicht rund, für die Unterforen hat der Aufruf heue mittag auch deutlich länger als jetzt gedauert

**Comment by ckruse** [comment]
hm. Merkwürdig. Mal im Auge behalten.
