### ISSUE TITLE
Gelesen-Markierung in einem Thread mit mehreren ungelesenen Beiträgen 

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#41]
Öffne ich einen Thread mit mehreren ungelesenen Beiträgen, dann wird nur der Beitrag als gelesen markiert, über den ich den Thread geöffnet habe. In der Thread-Ansicht ist das nachvollziehbar, in der Nested-Ansicht habe ich dann aber eigentlich alles auf dem Schirm und lese es auch. 

In CF4 wurden bei Öffnen eines Threads alle Beiträge im Thread als gelesen markiert. Meine ich mich jedefalls zu erinnern...

Man kann vermutlich in beiden Versionen Pros und Contras sehen, aber ich finde die alte Implementierung besser.

**Comment by ckruse** [comment]
Bist du sicher, dass auch nach einem Reload die Beiträge nicht als gelesen markiert werden? Denn eigentlich[tm] ist das Verhalten so:

- Thread laden
- Gelesen-Markierung setzen
- Thread rendern
- Beiträge, die noch nicht gelesen sind, als gelesen markieren

Das heisst, beim nächsten Laden der Threadliste bzw des Threads sollten alle Beiträge markiert sein. Hier in meiner lokalen Test-Installation kann ich das Verhalten auch verifizieren.

**Comment by Rolf-B** [comment]
Ja, bin ich. Gerade nochmal probiert (Thread 1747505). Einstieg über Beitrag 1751090 (RR von 17;46), auch über das Root Posting. Aber die 1751089 bleibt ungelesen (RR 17:41).

Expliziter Klick auf "Thread als gelesen markieren" (in der Nested-Ansicht des Threads auf Posting 1751090) macht die blaue Farbe von m1751089 weg - ups, und noch mehr

**Comment by Rolf-B** [comment]
f*ck , den Button "close and comment" hatte ich falsch verstanden :)

**Comment by Rolf-B** [comment]
Update: Ich habe gerade auf den zweiten Beitrag eines Threads geklickt, der für mich noch komplett ungelesen war. Dieser Klick hat den ganzen Thread als Gelesen markiert.

**Comment by ckruse** [comment]
Das Problem ist ein anderes. Aus einem mir noch nicht erfindlichen Grund funktionierte die Gelesen-Markierung gar nicht mehr. Application server neu gestartet, jetzt gehts wieder…

**Comment by Rolf-B** [comment]
Ok, deshalb kriege ich es nicht mehr reproduziert :)
