### ISSUE TITLE
Unterschied Vorschau - Postingausgabe

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#43]
Ich habe im Forum als Abschied "_Rolf_" gespeichert, ohne Linefeed dahinter. Als Signatur steht mein "sumpsi - posui - clusi". Das Forum generiert darus als Posting-Inhalt:

~~~
_Rolf_
--
sumpsi - posui - clusi
~~~

und zeigt dazu diese Vorschau (Github übrigens auch):

![image](https://user-images.githubusercontent.com/34056213/60101793-b6225700-975c-11e9-9755-728b85eda5ab.png)

Nach Speichern des Beitrags sieht es dann aber so aus:

![image](https://user-images.githubusercontent.com/34056213/60101951-fe417980-975c-11e9-9812-1ac66c419b11.png)

Bitte gleichziehen :)
_Rolf_

**Comment by ckruse** [comment]
Nee, da wird nicht gleichgezogen :-) die Korrektur auf Server-Seite ist für Legacy-Kompatibilität (weil User das schon jahrelang so benutzt haben), aber es ist kein korrektes Markdown. Die Vorschau zeigt es korrekt.

Das gleiche wirst du übrigens auch bei Zitaten ohne folgende Leerzeile beobachten können, also

~~~
> foo
bar
~~~

statt

~~~
> foo

bar
~~~

**Comment by Rolf-B** [comment]
Das ist jetzt aber Käse. Vorschau und Posting sollten identisch sein. Wie auch immer man das erreicht.

**Comment by MatthiasApsel** [comment]
Siehe #27
