### ISSUE TITLE
Ausgeblendete Threads werden bei neuen Postings wieder eingeblendet

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#50]
Ein ausgeblendeter Thread erscheint wieder in der Hauptansicht, wenn eine neue Antwort gespeichert wurde. Wenn der Thread danach wieder vollständig gelesen ist (oder entsprechend markiert wird), wird der Thread nach einem Reload der Hautpansicht wieder ausgeblendet.

**Comment by ckruse** [comment]
Sicher, dass das nicht nur das nachladen via JS betrifft?

**Comment by auge8472** [comment]
> Sicher, dass das nicht nur das nachladen via JS betrifft?

Das kann ich dir nicht sagen.

1. Ich blende einen Thread in der Hauptansicht über den Button aus. Dazu wird JS benutzt.
2. Eine Antwort wird geschrieben und gespeichert. Der Thread taucht mit der mit dem Glöckchen markierten Antwort wieder in der Hauptansicht auf.  Auch dazu wird JS benutzt.
3. Ich lese die neue Antwort in einem neuen Tab. Der Thread wird in der Hauptansicht nicht eingeklappt und das Glöckchen bleibt, aber `:visited` greift.
4. Ich lade die Hauptansicht über den Reload-Button des Browsers neu. Der Thread wird dabei ausgeblendet.

Das ist das, was ich beobachte.
