### ISSUE TITLE
Anderes Icon für Baum abonnieren

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#52]
Ich würde den Briefkasten vorschlagen https://fontawesome.com/icons/mailbox?style=solid oder ähnlich. Der Brief ist imho zu sehr mit der Mail verbunden.

**Comment by ckruse** [comment]
Wir können nur die Icons von Font Awesome 4 benutzen. Die findest du z.B. hier: <https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg>

Font Awesome 5 hat eine andere Lizenz.

**Comment by MatthiasApsel** [comment]
https://fontawesome.com/v4.7.0/icon/bookmark

https://fontawesome.com/v4.7.0/icon/newspaper-o

https://fontawesome.com/v4.7.0/icon/sticky-note-o

https://fontawesome.com/v4.7.0/icon/paperclip

**Comment by ckruse** [comment]
Ich find die ehrlich gesagt alle nicht so richtig prickelnd…

**Comment by ckruse** [comment]
https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/eye.svg wegen beobachten?

**Comment by ckruse** [comment]
Ja, ich glaube das gefällt mir.

![Bildschirmfoto vom 2019-07-05 14-18-28](https://user-images.githubusercontent.com/175095/60721988-dfe33700-9f2f-11e9-9f06-5ae23342b93b.png)

![Bildschirmfoto vom 2019-07-05 14-18-59](https://user-images.githubusercontent.com/175095/60721995-e40f5480-9f2f-11e9-934e-22f5d55dcb0d.png)

**Comment by MatthiasApsel** [comment]
Das ist auch eine gute Idee.
