### ISSUE TITLE
Benachrichtigungen über Aktivität in einem abonnierten Thread wird nicht automatisch gelöscht

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#53]
Wenn ich Benachrichtigungen über Antworten auf abonnierte Postings habe, wird der Zähler in der Hauptansicht nicht verändert, wenn ich eines dieser Postings öffne. Ich lese die Postings in der Einzelansicht.

Die Einstellung „Benachrichtigungen für Aktivität in abonnierten Beiträgen automatisch löschen“ ist aktiviert.

**Comment by ckruse** [comment]
Du meinst, dass in der Thread-Liste die Zahl der Benachrichtigungen sich nicht ändert, wenn du etwa ein Posting in einem neuen Tab aufmachst?

**Comment by auge8472** [comment]
Ja, genau das. In der 4-er Version wurde die Anzahl der Benachrichtigungen heruntergezählt, wenn ich ein Posting, für das es eine benachrichtigung gab, (wo und wie auch immer) geöffnet habe. Momentan wird die angezeigte Anzahl nur mit dem neuladen der Seite aktualisiert.

**Comment by ckruse** [comment]
Siehe #38 ;-)

**Comment by ckruse** [comment]
sollte jetzt implementiert sein.
