### ISSUE TITLE
Manche Benachrichtigungen werden nicht gelöscht

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#54]
Manche Benachrichtigungen überleben auch wenn der Beitrag längst gelesen ist. Hängt möglicherweise mit der nested-Ansicht zusammen.

https://forum.selfhtml.org/notifications/998852

führt zu https://forum.selfhtml.org/self/2019/jun/26/ausrichtung-von-fotos/1751443#m1751443 (Seite nicht gefunden)

Der richtige Beitrag wäre

https://forum.selfhtml.org/self/2019/jun/26/ausrichtung-von-fotos/1751442#m1751442

**Comment by ckruse** [comment]
Zur Zeit werden Mention-Benachrichtigungen noch nicht gelöscht, ja.

**Comment by MatthiasApsel** [comment]
Es ist aber keine Erwähnung und außerdem stimmt die URL in der Weiterleitung nicht, m175144***3*** statt m175144***2***!

**Comment by ckruse** [comment]
Ich denke eher, dass da deine Beobachtung nicht so richtig stimmt. Ich glaube dir, dass die Notification weitergeleitet hat auf 2, aber ich denke nicht, dass sie auf 3 hätte weiterleiten sollen.

**Comment by MatthiasApsel** [comment]
Einspruch: Der Text der Notifikation lautet (ich hab sie noch) 'Gunnar Bittersmann hat einen neuen Beitrag geschrieben: „Ausrichtung von fotos“' Erstellungszeitpunkt 28.06.2019 06:43 Gunnars Beitrag hat ebenfalls den Erstellungszeitpunkt 28.06.19 06:34.

**Comment by MatthiasApsel** [comment]
EInspruch zurückgezogen. 1. ist 34 nicht 43 und 2. wurde der Beitrag von :43 gelöscht. Es gibt also eine Notifikation, die auf ein gelöschtes Posting verweist.

**Comment by ckruse** [comment]
Ok, das ist möglich. Das ist dann aber trotzdem ein Problem, das sollte nicht passieren…  mal drüber nachdenken, was in dem Fall passieren sollte.

**Comment by MatthiasApsel** [comment]
Diese Frage hatten wir glaube ich in V4 auch schon mal. Da war deine Aussage, dass du gesendete Notifikationen nicht löschen und auch keine Notifikation hinterherschicken wolltest, wenn ich mich recht erinnere.

**Comment by ckruse** [comment]
Meh, scheiss Automatismen… ;-)

Ja, hatten wir. Ich habe da bei einer Löschung die Notification entfernt. Das würde ich hier auch wieder tun, aber das Problem tritt in der Tat bei einem Restore dann auf… der User würde sich wundern, dass er nicht benachrichtigt wurde 🤯
