### ISSUE TITLE
Dialogfenster schließt nicht bei [Esc]

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#57]
Das Dialogfenster zur Emoji-Auswahl schließt nicht beim Drücken der Escape-Taste.

**Comment by ckruse** [comment]
OS, Browser, Version?

Hier schließt es nämlich…

**Comment by MatthiasApsel** [comment]
Hier schließt es auch. (FF, Win)

**Comment by ckruse** [comment]
@gunnarbittersmann ping?

**Comment by gunnarbittersmann** [comment]
Firefox, macOS. Jetzt schließt es auch. Hm.

**Comment by ckruse** [comment]
Dann schließe ich das mal. Bei Bedarf wieder melden :-)
