### ISSUE TITLE
Draft wird nach Speichern nicht immer gelöscht

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#6]
Kein klares Fehlerbild, möglicherweise eine Race Condition.

Passiert sowohl bei new als auch bei edit.

Bei new kommt verschärfend hinzu, dass man dann für eine neue Antwort zum gleichen Posting (was den geschwätzigeren unter uns schonmal passiert) den alten Beitrag als Draft angeboten bekommt.

**Comment by ckruse** [comment]
Ich habe da mal einen Versuch eines Fixes commited, ich hoffe, das ist damit behoben…

**Comment by Rolf-B** [comment]
Meld! Siehe aktuellen Forenthread

**Comment by ckruse** [comment]
Hehe, ich denke, ich weiß jetzt, warum das der Fall ist:

~~~js
  resetSaveTimer() {
    if (this.timer) {
      window.clearTimeout(this.timer);
    }

    this.timer = window.setTimeout(this.saveDraft, 5000);
  }
~~~

Diese Funktion wird mit einem Key-Event ausgeführt. `saveDraft` speichert einfach nur das Draft im localStorage.

~~~js
  deleteDraft() {
    const key = this.props.form.action;
    localStorage.removeItem(key);
    this.toggleRestoreDraft(false);
  }
~~~

Diese Funktion wird ausgeführt, wenn das Formular abgesendet wird. Wie sie sehen, sehen sie nichts in Hinblick auf das abbrechen des Timers… :rofl:
