### ISSUE TITLE
Felder im Adventskalender zu schmal

### ISSUE THREAD

**Issue by J-Berkemeier** [ckruse/cforum_ex#607]
Im aktuellen [Adventskalender](https://forum.selfhtml.org/advent/2021) sind die Felder für die Tage zu schmal. Lange Worte gehen bis ins Nachbarfeld. 

Wäre es möglich, die Tage breiter zu machen, also andere flex-Struktur und ach andere Breakpoints?

Könnte für den ganzen Kalender die automatische Trennung angeschaltet werden?

**Comment by J-Berkemeier** [comment]
Siehe auch https://forum.selfhtml.org/verein/2021/nov/29/logo-fur-adventskalender/1794502#m1794502

**Comment by ckruse** [comment]
Fixed
