### ISSUE TITLE
Abstimmen über Zitatvorschläge führt zur einzelnen Ansicht des bewerteten Zitats

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#64]
Wenn, wie es momentan mit drei Zitatvorschlägen der Fall ist, mehrere Zitate zur Abstimmung stehen und ich über eines abstimme, ist nach der Abstimmung nur noch das Zitat, über das ist abgestimmt habe, zu sehen. Die anderen (aktuell) beiden Zitate werden nicht mehr angezeigt. Ich muss erneut den Link zu den zu bewertenden Vorschlägen bemühen, um über die anderen Vorschläge zu befinden.

Ich vermute eine Weiterleitung im Zuge der Abstimmung.

**Comment by ckruse** [comment]
Ja, hier fehlt noch das JS, dass bei den Thread-Aktionen schon dafür sorgt, dass die Seite nicht verlassen werden muss…
