### ISSUE TITLE
Mentions werden in der Postingvorschau nicht aufgelöst

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#65]
Nachdem ich in einem Postingentwurf einen Benutzer für ein @Mention aus der Vorschlagsliste ausgewählt habe, wird das Mention in der Textarea gesetzt, in der Vorschau aber nicht passend markiert. Das Mention bleibt dort einfacher Text. Nach dem Abschicken des Postings wird das Mention aufgelöst und funktioniert.

Dass es in der Vorschau als normaler Text angezeigt wird, hat mich verwirrt. Ich dachte beim ersten Mal, dass ich etwas falsch eingegeben hätte.

**Comment by ckruse** [comment]
Nachvollziehbar, aber nicht so ohne weiteres lösbar. Mentions können client-seitig nicht aufgelöst werden… die brauchen Meta-Informationen vom Server. Genauer gesagt ist es sogar so, dass auf Server-Seite Mentions umgeschrieben werden von `@User` zu `[@User](/path/to/profile){:.registered-user}` - das kann der Markdown-Parser nicht leisten.

Was ich damit sagen will: das Problem ist mir bekannt, aber ich weiss nicht so recht, was man dagegen tun sollte.

**Comment by auge8472** [comment]
Die Metainformationen vom Server zu holen, sollte doch kein Probklem sein. Bei der Auswahl der passenden Einträge für die Erzeugung des Mentions geschieht das doch auch, oder? Bliebe das Parsen der Vorschau. Dazu kann ich natürlich nichts qualifiziertes sagen.

Vielleicht würde eine farbliche Hervorhebung auch ohne Verlinkung zum Profil schon reichen, um dem Schreiber zu verdeutlichen, dass das Mention als solches erkannt wurde. Das war für mich *das*, was mir als Rückmeldung fehlte. Ich hatte jedenfalls noch nie das Bedürfnis, aus der Vorschau heraus zu versuchen, das Profil des jeweiligen Benutzer aufzurufen.

**\*btw\*** Deine Antwort *hier* ist wieder mal ein Beispiel für die Notwendigkeit von Beispieldatensätzen wie example.com einer ist. Ilya Solovyov, der bei Github den Benutzernamen "user" (extra nicht gementiont) hat, wird diese Wahl wohl auch schon x-mal bereut haben. ;-)

**Comment by ckruse** [comment]
hehe. Ich hatte es extra in Code-Zeichen gepackt, aber Github parsed das leider nicht in Email-Replys.

Bzgl der Meta-Informationen: die Meta-Informationen, die ich benötige, seher eher so aus:

~~~
mentions: [
  {pos: 10, mention: '@user', user: 10}
]
~~~

Das krieg ich halt nur vom Server. Es sei denn, ich implementiere den Algorithmus Client-seitig ein zweites mal…

**Comment by auge8472** [comment]
Ich denke, das Issue hat lange genug vor sich hingegammelt. ;-)

**Comment by ckruse** [comment]
Ja sorry, ist mir einfach zu viel Arbeit…
