### ISSUE TITLE
Auswählen von Text im Editor

### ISSUE THREAD

**Issue by MarcHaunschild** [ckruse/cforum_ex#66]
Texte im Editor können mit der Maus nur im sichtbaren Teil ausgewählt werden. Zieht man die Maus mit gedrückter Maustaste nach unten, scrollt der Text nicht automatisch mit.

Mit Tastatur geht es. Gefunden im Safari auf aktuellem MacOS

**Comment by ckruse** [comment]
Das halte ich für einen Bug im Safari… sowohl Chrome als auch Firefox machen es richtig.

**Comment by ckruse** [comment]
Ich wüsste auch nicht, wie ich das verursachen sollte… ich greife in das Scrolling gar nicht ein.

**Comment by MarcHaunschild** [comment]
Ist mir früher nie aufgefallen (in der Version 4) und ich nutze vor allem Safari...

**Comment by ckruse** [comment]
Ja, das glaube ich dir. Du siehst mich nur ratlos :-)

**Comment by MarcHaunschild** [comment]
Hier im Editor auf Github funktioniert es auch im Safari. Aber das hilft dir natürlich auch nicht weiter...

**Comment by ckruse** [comment]
Ich denke, das habe ich jetzt gefixed. Kannst du das bitte verifizieren?

**Comment by ckruse** [comment]
(bei mir zumindest geht es jetzt)

**Comment by MarcHaunschild** [comment]
Bei mir (iPhone) geht es auch!

Great job!

--
Mit freundlichen Grüßen

Marc Haunschild
www.mhis.de<http://www.mhis.de>

Am 14.07.2019 um 09:53 schrieb Christian Kruse <notifications@github.com<mailto:notifications@github.com>>:


(bei mir zumindest geht es jetzt)

**Comment by ckruse** [comment]
👍
