### ISSUE TITLE
Hauptansicht ohne Pagination, Paginationsnavi wird dennoch angezeigt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum_ex#67]
In meinem Profil ist für die Hauptansicht die Pagination abgeschaltet. Dennoch wird die Navigation mit aktuell sechs Seiten für die Ansicht "all" oberhalb der Threadliste angezeigt.

![Paginationsnavi trotzdem Pagination abgeschaltet ist](https://user-images.githubusercontent.com/1734660/60503557-43ffc400-9cc0-11e9-8dd9-97b9c4bbd1fc.jpg)

Beachte im Screenshot bitte den Anfasser des Scrollbalkens, die für eine paginierte Darstellung viel zu kurz ist, als Beweis für die unpaginierte Darstellung der Threadliste.

**Comment by ckruse** [comment]
😂 da hab ich mich selbst in den Fuß geschossen. Die Paginierung unten hab ich abgeschaltet, aber oben habe ich sie nicht gesehen, weil mein Editor die vorherige Scroll-Position wiederhergestellt hat und die obere Paginierung um zwei Zeilen herausgescrollt war.
