### ISSUE TITLE
Margin von cf-alert macht Menü unbedienbar

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#7]
Im Stylesheet gibt es diese Regel:

.cf-alert,.cf-error,.cf-info,.cf-success,.cf-warning {
    padding: 1em;
    margin: 0 0 1em;
    border: 1px solid transparent;
    border-radius: 4px;
    box-shadow: 0 0 6px #666
}

Der Margin führt bei .cf-alert dazu, dass die Popup-Nachricht transparent das Menü überlagert, d.h. man muss warten bis die Nachricht ausgeblendet ist, bevor man im Menü etwas klicken kann.

Mein persönliches Stylesheet enthält jetzt 

.cf-alert { 
  margin: 0;
}

**Comment by ckruse** [comment]
Der Margin ist natürlich bescheuert. Danke.
