### ISSUE TITLE
Etwas ist schief gegangen bei kurzer Antwort

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#70]
Bernd meldet [im Forum](https://forum.selfhtml.org/meta/2019/jul/03/fehler-beim-antworten/1751812#m1751812), dass bei sehr kurzer Antwort ("Danke!") das Forum die generische Fehlermeldung "Oops! Etwas ist schief gegangen." zeigt.

Das ganze ist bei mir nicht reproduzierbar, ich erhalte stattdessen oberhalb des Eingabefelds den Hinweis: "Beitragstext sollte mindestens 10 Zeichen haben".

Irgendwo steckt da wohl ein schwierig zu reproduzierender Fehler.

**Comment by ckruse** [comment]
Nee, das habe ich schon gestern gefixed. Deshalb konntest du es nicht reproduzieren :-) das war vergessener Debug-Code, siehe 0453de2acd758ee8913fbef4b2f55f90df1dfbde
