### ISSUE TITLE
Beitrag doppelt gepostet

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#71]
Ich habe eben [diesen Beitrag ](https://forum.selfhtml.org/self/2019/jun/26/bleicher-mond/1751918#m1751918) abgeschickt und dabei direkt danach offenbar [diese Kopie](https://forum.selfhtml.org/self/2019/jun/26/bleicher-mond/1751917?view_all=yes#m1751917) erstellt, ohne bewusst etwas getan zu haben; der Beitrag wurde quasi zweimal gepostet.

**Comment by ckruse** [comment]
Also, wenn der Beitrag zweimal gepostet wurde, dann hat irgendwie eine Resubmission stattgefunden. Dass die Software das zweite Posting von sich aus erzeugt hat, glaube ich nach Prüfung des Codes nicht… ich kann das auch nicht nachstellen.

**Comment by campingrider** [comment]
Hm, obwohl ich nicht genau weiß, wie es dazu kam, vermute ich, dass du Recht hast. Ist mir bisher auch nicht nochmal passiert. Also close.
