### ISSUE TITLE
Worüber stimmt man ab? Sperrung oder Löschung?

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#73]
Wenn ich "Abstimmung über einen Beitrag starten" klicke, steht da

> Sperr-Abstimmung (1/5)  
Der Beitrag und die folgenden Antworten werden **gelöscht**. Der angegebene Grund: (...)

Was ich schon merkwürdig fand. Es ist doch eine Sperr-Abstimmung?!

Und dann, nachdem die Stimmzahl erreicht wurde (wenn auch eins zu früh, siehe anderes Issue), heißt es 

> Sperr-Abstimmung (4/5)
Der Beitrag und die darauf folgenden Beiträge wurden geschlossen. Der angegebene Grund:  (...)

Ich bin jetzt aber nicht hinreichend aufmerksam gewesen und habe mir den Text vor meinem Abstimmklick nicht gemerkt. Kann es sein, dass die Meldungstexte hier durcheinander gehen?

**Comment by MatthiasApsel** [comment]
In V4 war das abhängig vom angegeben Grund. Es gab beide Möglichkeiten.

**Comment by campingrider** [comment]
Vermutlich sollte dann aber sowohl die Benennung der Abstimmung als auch der erläuternde Text entsprechend auf die eingestellte Reaktion bei erfolgreicher Abstimmung geändert werden. Der Button kann, denke ich, weiter auf "Sperrabstimmung" lauten (bei der Grund-Auswahl wird ja dann differenziert), aber bei einer laufenden Abstimmung, die entweder zu Sperrung oder zu Löschung führt sollte dann auch dranstehen "Sperrabstimmung" oder "Löschabstimmung", imho.
