### ISSUE TITLE
Nachfrage: Bewertungen und edits

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#75]
Im Forum [kam die Frage auf](https://forum.selfhtml.org/meta/2019/jul/07/fur-welche-postingversion-gelten-eigentlich-die-bewertungen/1752284#m1752284), auf welche Version sich Bewertungen beziehen, wenn das Posting editiert wurde. Falls das noch nicht der Fall ist, sollte es für unangemeldete User und User ohne spezielle Rechte nach einer Bewertung nicht mehr möglich sein, das Posting zu bearbeiten.

**Comment by ckruse** [comment]
Habe ich gesehen, ja, aber das sehe ich anders… so wichtig ist es auch nicht zu wissen, auf welche Version sich die Bewertung bezieht. Und für anonyme User bedeutet das eine deutliche Reduktion des Komforts.

**Comment by campingrider** [comment]
Es besteht halt die Gefahr einer nachträglichen Sinnentstellung, und auf einmal stehen dann da Nazi-Parolen mit positiven Bewertungen. Wobei das ja dann im Zweifel auch gelöscht werden würde.

**Comment by ckruse** [comment]
Klar, das ist möglich. Und dann sieht man die Edits in den Versionen. Dafür sind sie da.

**Comment by ckruse** [comment]
Ich mach das mal zu… bei fragen einfach nachhaken
