### ISSUE TITLE
Mentions ohne Leerzeichen

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#76]
Für die [Mention durch Matthias](https://forum.selfhtml.org/meta/2019/jul/07/fur-welche-postingversion-gelten-eigentlich-die-bewertungen/1752349#m1752349) habe ich keine Benachrichtigung bekommen - vermutlich aufgrund des direkt folgenden Doppelpunkts. Vermutlich sollte bei der Prüfung auf Mentions im Misserfolgsfall auch der String abzüglich des letzten Zeichens geprüft werden oder alternativ bestimmte Zeichen am Ende entfernt werden, damit Mentions vor dem Satzzeichen auch funktionieren.

**Comment by campingrider** [comment]
Sorry, der Titel ist natürlich Quatsch. Sollte Mentions am Satzende heißen, kann ich aber via mobil leider nicht ändern :(

**Comment by ckruse** [comment]
Ist inzwischen gefixed (sorry, hatte zwischendurch den Überblick ein wenig verloren)
