### ISSUE TITLE
Link zu gelöschtem Posting sollte aussagekräftige Fehlermeldung bieten

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#78]
Es kommt immer wieder vor, dass irgendwo auf ein gelöschtes Posting verlinkt wird. Im Moderationsbereich sowieso, aber auch im öffentlichen Bereich.

Im Moment führt ein Klick auf eines dieser Postings auf die generische "Oops, da ist was schiefgelaufen"-Seite. Der User denkt, die Software hat da wohl einen temporären Fehler (kommt ja mit dieser Meldung immer mal wieder vor).

Viel sinnvoller wäre es aber, hier eine aussagekräftigere Meldung zu werfen. Zum Beispiel: "Dieses Posting wurde gelöscht." mit Links zurück zur Forumshauptseite, zur zugehörigen Forumsübersicht und ggf. zum zugehörigen Thread-Opener. Moderatoren / Admins könnten dann an der Stelle dann auch die Möglichkeit zum Wechsel in die Admin-Sicht angeboten bekommen.

Das würde an vielen Stellen helfen, Missverständnisse zu vermeiden und die grenzwertige Erfahrung, aus dem normalen Forums-Look-and-Feels auf eine ungestylte Fehlerseite geworfen zu werden, verringern.

**Comment by ckruse** [comment]
Die Fehlerseiten sind jetzt gestyled; wenn du ausführlichere Texte haben willst, tob dich aus, siehe <https://github.com/ckruse/cforum_ex/tree/master/lib/cforum_web/templates/error> :-)

**Comment by campingrider** [comment]
Bloß um dazu mal ein Lebenszeichen loszuwerden: Ich schau mir das die nächsten Tage mal in einer ruhigen Minute an.

**Comment by ckruse** [comment]
@campingrider ping? :-)

**Comment by campingrider** [comment]
Hehe, ja. Bin grad noch ein paar Tage im Urlaub und noch nicht dazu gekommen, den Laptop mal anzuwerfen^^

**Comment by ckruse** [comment]
viel Spaß im Urlaub!

**Comment by MatthiasApsel** [comment]
@campingrider ping? :-)
