### ISSUE TITLE
Archivpostings mit Tabellen unleserlich

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#79]
Durch den geänderten Markdown-Parser (s.a. https://github.com/ckruse/cforum_ex/issues/55) werden vorhandene Postings unleserlich, Bsp. https://forum.selfhtml.org/self/2019/may/22/fehlende-img-datei-ueberspringen/1749252#m1749252

Entweder einen Markdown-Parser verwenden, der mit der zuvor verwendeten Syntax klarkommt, oder das Tabellenmarkdown in allen archivierten Postings so umwandeln, dass eine Tabelle gerendert wird.

**Comment by JuliusPC** [comment]
Noch ein Beispiel: <https://forum.selfhtml.org/self/2016/mar/23/erster-prototyp-des-php-forums/1664439#m1664439>  
(Das von Gunnar wurde anscheinend gefixt?!)

**Comment by ckruse** [comment]
Ich denke nicht, dass ich den Bug fixen werde.

**Comment by JuliusPC** [comment]
Ähm, stimmt. Tabellen ohne Kopf einen Kopf zu spendieren, ist schwieriger als anders herum...

Dies ist die [Bibliothek](https://github.com/ckruse/cfmarkdown), die Markdown parst und der das dann wer beibringen müsste, oder? :see_no_evil:

**Comment by ckruse** [comment]
Ja und nein. Ja, das ist die Software, die das Markdown zu HTML umwandelt und der müsste man es vermutlich beibringen.

Diese Bibliothek allerdings nutzt selber „nur“ [markdown-it](https://github.com/markdown-it/markdown-it) (mit ein paar Anpassungen).
