### ISSUE TITLE
Ist Mathjax kaputt?

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#80]
https://forum.selfhtml.org/meta/2019/jul/10/test-mathjax/1752643

**Comment by gunnarbittersmann** [comment]
Zusätzlich dazu: nicht alles LaTeX wird gerendert, siehe https://forum.selfhtml.org/self/2019/jan/23/mathematik-zur-wochenmitte/1741454#m1741454

**Comment by ckruse** [comment]
Ersteres war in der Tat ein Bug, ich hatte das KaTeX-CSS vergessen einzubinden.

Zweiteres ist ein Upstream-Bug in KaTeX. Da müssen wir auf einen Fix von dort warten.
