### ISSUE TITLE
Bild einfügen bei Mail

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum_ex#81]
Beim Verfassen einer Mail fehlt der Button zum Bild einfügen über dem Eingabefeld.

**Comment by ckruse** [comment]
Working as intended. Bilder in Mails sind abgeschaltet, aus privacy & rechtlichen Gründen. Wir müssten die auf Copyright-Verstöße prüfen, und ich will nicht in den Mails der User rumschnüffeln.

**Comment by gunnarbittersmann** [comment]
?? Wieso das denn? 
Wenn der Absender einem Empfänger ein Bild zusendet, ist das doch keine Veröffentlichung des Bildes.

**Comment by ckruse** [comment]
Das magst du so sehen. Das sieht die Rechtsprechung aber anscheinend anders. Du siehst doch, unter was für einem Druck Unternehmen wie Facebook (mit Whatsapp) und Signal stehen…

**Comment by gunnarbittersmann** [comment]
Dann müsste ja jeder Mail-Povider das Anhängen von Dateien jeglicher Art schon längst verhindert haben. Haben sie aber nicht.

Vielleicht sollten wir mal einen (vermutlich noch zweistelligen) Betrag in die Hand nehmen und die Auskunft eines darauf spezialisierten Anwalts einholen?

Außerdem wird es ja technisch gar nicht unterbunden, Bilder in DMs zu hängen: https://forum.selfhtml.org/meta/2019/aug/07/mathematik-zur-wochenmitte/1754982#m1754982 

Das führt aber zu inakzeptabler UX – grundlos, weil das Problem nicht gelöst wird, falls das Problem überhaupt eins ist.

**Comment by ckruse** [comment]
Emails und DMs sind nicht das gleiche und schon gar nicht das selbe. So einfach ist das nicht.

Ansonsten ist das technisch auch kein Anhang, sondern halt ein Link auf eine externe Resource. Das kann ich halt nicht verhindern. Das wird man immer machen können, notfalls über einen externen Hoster.

**Comment by ckruse** [comment]
Vergessen: eine Beratung durch einen Anwalt fände ich hilfreich. /cc @MatthiasApsel @campingrider

**Comment by MatthiasApsel** [comment]
Die braucht man nur, wenn man das machen möchte. Solange wir keine Bilder in DMs erlauben, brauchen wir auch keinen Anwalt. Und der Anwalt wird uns auch nicht garantieren, dass seine Meinung rechtssicher ist. Also wird es rausgeworfenes Geld sein, dass uns im Klagefall gar nicht gebracht hätte.

**Comment by gunnarbittersmann** [comment]
Bilder in DMs möchte man. Zumindest möchten das alle, die bei den Matherätseln mitmachen.

Und ist es nicht so, dass man durch Einholung der Auskunft eines Anwalts doch eine Sicherheit hat, weil im Fall einer Abmahnung o.ä. der Anwalt (bzw. dessen Versicherung) dafür aufkommt?

**Comment by ckruse** [comment]
lol, nein 😂 der Anwalt gibt dir keine Garantien. Und das formuliert er auch so. Er gibt dir lediglich eine fachliche Beratung.
