### ISSUE TITLE
Forum zeigt nur 2 Seiten

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#84]
Linuchs wies darauf hin: selbst wenn ich "gelesene Seiten anzeigen" einschalte, bekomme ich maximal zwei Seiten mit Beiträgen angeboten. Ist das ein Feature zum Sparen von Serverleistung? Oder ein Bug?

**Comment by ckruse** [comment]
Weder, noch - die anderen Threads sind einfach archiviert worden

**Comment by ckruse** [comment]
Nachtrag: in `/all` gibt es auch mehr Seiten

**Comment by ckruse** [comment]
(Weil: Archivierungs-Einstellungen: Maximale Anzahl an Threads: 50)

**Comment by Rolf-B** [comment]
So schnell wird archiviert? Na gut. 

Folgefrage: Warum werden mir archivierte Threads wie ungelesen angezeigt? Z.B. https://forum.selfhtml.org/self/2019/jun/25/foreach-anpassen/1751106 - da habe ich mitdiskutiert, der ist nicht ungelesen...

**Comment by Rolf-B** [comment]
Achso, noch eine Folgefrage: Hat CF4 nicht die archivierten Beiträge ganz normal mit angezeigt? Weiß ich nicht mehr...

**Comment by ckruse** [comment]
In CF4 wurden Gelesen-Markierungen nicht zurückgesetzt, ja. In V5 schon, siehe <https://github.com/ckruse/cforum_ex/blob/master/lib/cforum/forums/archiver_job.ex#L90>

Hintergrund ist, dass die Datenmenge einfach zu groß wurde. Ich hatte damals schon einen Schwung gelöscht (von Postings, die seit mindestens einem Jahr archiviert waren), ist keinem aufgefallen :smiling_imp:
