### ISSUE TITLE
"Punkt" in der Punkteanzeige bei dynamischer Änderung

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#86]
Eine kleinere Sache, aber: Wird die Punktzahl oben in der Kopfleiste dynamisch, d.h. ohne Reload, angepasst (z.B. weil man eben eine Bewertung erhalten hat), dann fehlt in Folge der . als Tausendertrennzeichen, der nach Reload standardmäßig angezeigt wird.

Vor Reload:

![image](https://user-images.githubusercontent.com/11651007/61187299-2e9b7a00-a670-11e9-8994-0a5f38c35f4a.png)

Nach Reload:

![image](https://user-images.githubusercontent.com/11651007/61187307-3ce99600-a670-11e9-848c-edd3b6056a23.png)

**Comment by ckruse** [comment]
Ja, ist mir auch schon aufgefallen. Ist ist übrigens ein guter erster Commit ;-) du musst hier:

<https://github.com/ckruse/cforum_ex/blob/master/assets/js/modules/user-notifications.js#L57>

`data.score` vorher durch die [I18N-API des Browsers](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) schicken.

**Comment by campingrider** [comment]
Ich versuch das mal!
