### ISSUE TITLE
Bearbeiten-Button für einen Beitrag wird angezeigt, wenn Frist vorbei ist

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#9]
Ein Beitrag, dessen Bearbeitungsfrist vorbei ist, zeigt immer noch den Bearbeiten-Button an. Klickt man ihn, kommt ein leerer Bildschirm mit "Access forbidden". Als User mit Admin-Rechten bemerkt man das vermutlich nicht.

**Comment by ckruse** [comment]
Sicher, dass der Edit-Button nicht angezeigt wurde, weil zu dem Zeitpunkt, als die Seite geladen wurde, die Zeit noch nicht abgelaufen war?

**Comment by Rolf-B** [comment]
Nein, bin ich nicht mehr, ich kann es bei älteren Beiträgen nicht mehr nachvollziehen. Ich bin aber sicher, dass ich einen Reload der Seite probiert hatte, bevor ich ein Issue aufgemacht habe.

Ich muss mal schauen ob der Button nur am gleichen Tag erscheint (Hypothese: das Bearbeiten wird auf Basis von DateTime verhindert, das Anzeigen des Buttons auf Basis von Date).

**Comment by ckruse** [comment]
Nö, das ist der identische Code, der das entscheidet.

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Anything new? Ansonsten würde ich das hier mal schließen :-)
