### ISSUE TITLE
Bewertungshistorie ist unsortiert

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum_ex#91]
Zitat [Forum](https://forum.selfhtml.org/meta/2019/jun/22/classic-forum-v5/1753384#m1753384):

Die Bewertungshistorie auf der persönlichen Seite ist unsortiert. Früher waren die neuesten Einträge oben.

**Comment by ckruse** [comment]
Welche Seite ist gemeint? URL? Weil die, die ich der Beschreibung nach anschauen würde ist sortiert:

~~~elixir
order_by: [desc: :created_at]
~~~

**Comment by ckruse** [comment]
Oh - da fällt mir auf, ich baue eine Map. Das zerstört die Sortierung 😂🤦‍♂️

**Comment by ckruse** [comment]
Nein, das wars auch nicht. Meines Erachtens ist das sortiert. Was ist gemeint?

**Comment by campingrider** [comment]
Hm, ich kanns leider auch nicht nachvollziehen/nachstellen. Vorschlag: Wir schließen das hier, solange, bis ggf. mal ein Screenshot oder anderweitig zusätzliche Daten zum Phänomen aufschlagen.
