### ISSUE TITLE
Kein Syntaxhighlighting für PHP

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#96]
`~~~php`
`$a = 3;`
`for ($i=1; $i<$a; $i++) {`
`   echo $i;`
`}`
`~~~`

sieht im Forum so aus:

![image](https://user-images.githubusercontent.com/34056213/61789773-d570da80-ae15-11e9-9942-e8facaff7f6e.png)

statt so:

~~~php
$a = 3;
for ($i=1; $i<$a; $i++) {
   echo $i;
}
~~~

**Comment by ckruse** [comment]
Das gilt nur für die Vorschau. Das Rendering auf dem Server sieht so aus:

![Bildschirmfoto 2019-07-24 um 13 34 39](https://user-images.githubusercontent.com/175095/61790556-d3a81680-ae17-11e9-8c6b-ce41249b4887.png)

Ich kann nicht alle Sprachen mitliefern, das würde zu einem mehrere MB großen Bundle nur für das Syntax-Highlighting führen.

**Comment by Rolf-B** [comment]
> "Ich kann nicht alle Sprachen mitliefern" 

Da stimme ich zu, aber ich hätte gedacht, dass HTML, CSS, JS, PHP und SQL zur Grundausstattung für SelfHTML gehören sollten. HTML ist vorhanden. Exoten wie Erlang oder Ruby braucht vermutlich keiner. :stuck_out_tongue: 

Das mag aber jetzt sein wie es will - wenn es nur die Vorschau wäre, würde ich jetzt die Schultern zucken und "issebenso" sagen. Aber es ist nicht nur die Vorschau. Bei mir ist die Darstellung, mit etwas Glück, für 10ms bunt und wird dann einfarbig. Gerade, als ich den Thread nochmal aufrief, blitzte kurz die Farbe auf und verschwand dann wieder.

Gucke ich in die Entwickler-Tools, sehe ich unter "Sources" eine HTML-Struktur, die nach Highlighting aussieht.

![image](https://user-images.githubusercontent.com/34056213/61809508-bb4af280-ae3d-11e9-8d98-04b6afcb75cd.png)

Aber im DOM sieht es anders aus, da steht

![image](https://user-images.githubusercontent.com/34056213/61809466-a3736e80-ae3d-11e9-87aa-1e871a355619.png)

Offensichtlich findet also bei mir ein Postprocessing statt, das das Highlighting entfernt. Bei Dir nicht. User-CSS habe ich entfernt. User-JS habe ich nicht.

Gibt es einen Schalter, den ich verstellen muss? Gefunden habe ich keinen.

**Comment by Rolf-B** [comment]
Hmm. Nachtrag: Ich sehe, dass das <pre> vor dem <code> einen className bekommen hat, und zwar mit einem Space vorneweg. Im Source war das nicht. Und im <code> Element ist zwischen block und language-php ebenfalls ein Space erschienen. Schraubst Du da am className Attribut herum, statt die classList zu verwenden?

**Comment by ckruse** [comment]
Ich habs jetzt zumindest mal nachstellen könne, im Chrome. Das ist dieses vermalledeite Auto-Hochlicht-Feature von Prism, vermute ich…

**Comment by Rolf-B** [comment]
Was auch immer du getan hast - es funktioniert jetzt :)

**Comment by ckruse** [comment]
Prism ausgetrickst :-)

**Comment by saxoneee** [comment]
Hello,

Wär es ein Unding, yarn in deinen Stack aufzunehmen und irgendeinen JS-Syntax-Highlighter hinzuzufügen? Das könnte man doch als optionale Dependency hinzufügen. Gerade bei SELFHTML finde ich es auch in der Vorschau wichtig, nen Highlighter zu haben. Sonst bläht sich die Beitragshistorie nur unnötig auf (und der Frust derer, die Probleme ohne H. haben). 
Dann könntest du deinen serverseitigen Code etwas reduzieren und das Aussehen dem überlassen, der dafür zuständig ist: dem Frontend.

henman aka saxoneee

P.S. ich bin jetzt nüchtern, aber furchtbar unausgeschlafen.

**Comment by ckruse** [comment]
Äh. Das ist ja genau das, was passiert? JS übernimmt das komplette Rendering. Das Problem ist ja, dass ich nicht alle Sprachen zum Frontend transportieren kann, weil ich dann einen mehrere MB großen JS-Blob zum Client schicken muss.

**Comment by ckruse** [comment]
(übrigens wird bereits Yarn und Webpack verwendet ;-)

**Comment by saxoneee** [comment]
Sorry, da war ich wirklich übermüdet. Könnte man dann nicht nen Ajax-Request beim Textschreiben machen, der nur das Syntax-Highlighting beinhaltet? Ich weiß: wtf? 
Klingt wild, aber vielleicht is es einfach spaßig zu konzipieren.

**Comment by ckruse** [comment]
Ich habe das jetzt mal umgestellt, das Syntax-Highlighting wird tatsächlich nur noch auf den Client gemacht. Und dort werden dann alle Sprachen geladen.
