### ISSUE TITLE
CSS-Vorschlag

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#97]
~~~css
.cf-posting-content.deleted * {
  color: darkred;
  text-decoration: line-through;
}
~~~

**Comment by ckruse** [comment]
Damit wird mir der Text zu unleserlich… zu wenig Kontrast durch das rot auf gelb, zu viel Ablenkung durch das line-through

**Comment by ckruse** [comment]
hab mal leicht andere Farben genommen…

**Comment by MatthiasApsel** [comment]
Danke. Gefällt mir gut. Es geht ja nur darum, die gelöschten Beiträge schnell zu identifizieren.

**Comment by MatthiasApsel** [comment]
Die Lesbarkeit ist natürlich auch ein Argument. Deshalb könnte man auf das line-through verzichten und stattdessen einen etwas breiteren Rahmen in der leicht anderen Farbe nehmen.
