### ISSUE TITLE
Private Nachrichten lassen sich nicht nach Partner sortieren

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum_ex#99]
Es wäre schön, wenn das ginge.

**Comment by ckruse** [comment]
Es kann nach Partner gefiltert werden (klick auf den Partner-Namen). Warum brauchst du da noch eine Sortierung nach Partner?

**Comment by MatthiasApsel** [comment]
Hm. Das war mir nicht bewusst (und funktioniert auch nicht, auch bei https://forum.selfhtml.org/mails?author=Camping_RIDER werden alle Mails angezeigt) Außerdem, wenn ich nach einem Autor suche, aber seinen Namen nicht genau kenne.
