### ISSUE TITLE
https://forum.selfhtml.org und https://forum.selfhtml.org/all liefern Fehler beim Laden

### ISSUE THREAD

**Issue by Rolf-B** [ckruse/cforum_ex#993]
Es ist nicht ganz konsistent, aber zumindest die Startseite, ohne jeden Path, liefert http404 und keine Inhalte. Zusätzlich enthält es das Einstiegs-Script, das auf dem body die js Klasse setzen soll, ohne nonce. Daraufhin gibt's in der Konsole eine Security-Fehlermeldung.

Ich bekomme definitiv eine http404 Response bei den URLs

https://forum.selfhtml.org/
https://forum.selfhtml.org/?srt=yes
https://forum.selfhtml.org/all?srt=yes

Im Admin-Modus funktioniert es dann wieder.

Laut Github hat sich nichts am Forum geändert, was zum Geier ist das los?

**Comment by ckruse** [comment]
Jemand[tm] hat das Blog-Posting „Navigation - alles inclusive“ auf Draft gesetzt, aber es hatte bereits einen Kommentar. Deshalb wurde das Posting aus der Liste entfernt. Beim erstellen des Baums wurde dann versucht das Root-Posting zu finden, das schlug fehl, deshalb gab es eine `NotFoundException`.

Fix ist in ein paar Minuten online.

**Comment by Rolf-B** [comment]
Herzlichen Dank. Ich weiß auch nicht, was Matthias geritten hat, diesen Dummy-Kommentar zu erstellen. Wenn man gewusst hätte, dass es daran liegt, hätte es vermutlich genügt, ihn einfach zu löschen. Oder?

Wie heißt es so schön: Nichts ist narrensicher, Narren sind viel zu kreativ. Dabei war Fasching doch 'rum und Matthias sollte seine Narrenkappe nicht mit nach Gastein genommen haben.

**Comment by Rolf-B** [comment]
Der Fehler mit der fehlenden Nonce ist noch da, der tritt immer noch gelegentlich auf wenn das Forum 404 meldet,

Testfall: <https://forum.selfhtml.org/self/blurb>

Hat aber jetzt keine Prio mehr.
